import { CharacterEpisode } from '../types/game';
import { ASSETS } from './assets';

/**
 * BIÊN NIÊN KÝ MỞ RỘNG TRẢI DÀI 5 CHƯƠNG (NGÀY 16 – 210+)
 * Tuyến truyện quy mô tiểu thuyết sâu sắc kết nối toàn bộ cư dân Hẻm 1102.
 * Mỗi chương mở khóa các biến cố lớn, mâu thuẫn gia đình, tình yêu, sự trả thù thương trường
 * và vinh quang ẩm thực truyền thống đánh bại đồ ăn nhanh công nghiệp.
 */
export const CHARACTER_EPISODES_EXPANDED: CharacterEpisode[] = [
  // =========================================================================
  // CHƯƠNG 2: TIỆM TRONG HẺM (NGÀY 16 – 50) — ĐỊNH HÌNH PHONG CÁCH & THỬ THÁCH
  // =========================================================================
  {
    id: 'bac_ba_ep_04',
    characterId: 'bac_ba',
    characterName: 'Bác Ba Tổ Trưởng',
    characterRole: 'Cựu Bếp Trưởng Gà Chợ Lớn 1990',
    avatar: ASSETS.bacba.front,
    episodeIndex: 4,
    title: 'Tập 4: Bốn Bàn Gỗ Dưới Giàn Hoa Giấy',
    subtitle: 'Ngày dọn vào căn nhà số 14 sâu trong hẻm',
    unlockDay: 16,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'bac_ba_ep_03',
    narrativeIntro: `Xe đẩy inox ngày nào nay đã được thay bằng căn nhà nhỏ số 14 với 4 bộ bàn gỗ mộc mạc dưới giàn hoa giấy đỏ rực. Bác Ba chắp tay ngắm nhìn quầy bếp mới, xúc động lấy ra một chiếc vá gỗ cán dài đã nhẵn bóng qua năm tháng.`,
    dialogueLines: [
      {
        speaker: 'Bác Ba',
        text: 'Có được 4 cái bàn ngồi đàng hoàng, bà con tới ăn không còn phải che dù né mưa nữa rồi. Nhìn mày, bác nhớ lại ngày đầu ông Võ Hòa mở tiệm...',
        mood: 'happy',
      },
      {
        speaker: 'Bác Ba',
        text: 'Chiếc vá gỗ này bác dùng suốt 10 năm ở Chợ Lớn. Nay tặng lại mày để vớt từng mẻ gà thơm thảo cho hẻm mình.',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Bác Ba trao kỷ vật thiêng liêng nhất đời làm bếp cho bạn. Bạn chọn việc gì đầu tiên trong ngày tân gia?',
    choices: [
      {
        id: 'bac_ba_04_seat_of_honor',
        label: 'Mời Bác Ba ngồi vào bàn số 1 danh dự, tự tay dâng đĩa gà chiên khai trương đầu tiên',
        kicker: '👑 BÀN DANH DỰ',
        reactionDialogue: 'Bác Ba mỉm cười lau giọt nước mắt hạnh phúc: "Được nếm mẻ gà đầu tiên của tiệm mới là phước của ông già này rồi."',
        causalityNotice: 'Bác Ba ban phước lành! Tăng độ hảo cảm và uy tín quán trong hẻm.',
        karmaEffect: { community: 20, craftsmanship: 15 },
        rewardReputation: 25,
        setsFlag: 'bacba_housewarming_honored',
      },
    ],
    summaryNote: 'Khai trương tiệm trong hẻm số 14 với 4 bàn gỗ. Bác Ba trao tặng chiếc vá gỗ gia truyền năm 1990.',
  },
  {
    id: 'bac_ba_ep_05',
    characterId: 'bac_ba',
    characterName: 'Bác Ba Tổ Trưởng',
    characterRole: 'Cựu Bếp Trưởng Gà Chợ Lớn 1990',
    avatar: ASSETS.bacba.front,
    episodeIndex: 5,
    title: 'Tập 5: Nồi Cháo Gà Trong Đêm Bác Ba Trúng Gió',
    subtitle: 'Tình làng nghĩa xóm sưởi ấm căn nhà tập thể cũ',
    unlockDay: 35,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'bac_ba_ep_04',
    narrativeIntro: `Chiều tối, quán đông nghịt khách nhưng không thấy bóng dáng quen thuộc của Bác Ba đi tuần qua. Cô Bảy vé số chạy hớt hải vào báo: "Bác Ba bị trúng gió nằm liệt giường từ trưa, nhà khóa trái không ai hay biết!".`,
    dialogueLines: [
      {
        speaker: 'Bạn (Chủ Quán)',
        text: 'Mọi người trông quán giùm em chút! Em nấu nồi cháo gà gừng nóng sang nhà xem bác thế nào ngay!',
        mood: 'tense',
      },
      {
        speaker: 'Bác Ba (Thều thào trên giường)',
        text: 'Khụ... Khụ... Bác già rồi, trở trời một cái là gân cốt rệu rã... Phiền mày với bà con quá...',
        mood: 'sad',
      },
    ],
    dilemmaPrompt: 'Bác Ba nằm đơn độc trong căn phòng nhỏ đơn sơ. Bạn quyết định chăm sóc người thầy này ra sao?',
    choices: [
      {
        id: 'bac_ba_05_care_soup',
        label: 'Đút từng thìa cháo gà tía tô nóng hổi cho bác, nhờ Tuấn shipper ghé tiệm thuốc mua thuốc cảm',
        kicker: '🍲 BÁT CHÁO GỪNG TÌNH NGHĨA',
        reactionDialogue: 'Húp xong bát cháo nóng toát mồ hôi, Bác Ba nắm chặt tay bạn: "Ơn này của mày, bác khắc ghi trong dạ."',
        causalityNotice: 'Bác Ba bình phục kỳ diệu! Cả hẻm cảm phục tấm lòng hiếu thảo của bạn.',
        karmaEffect: { community: 30, craftsmanship: 10 },
        setsFlag: 'bacba_health_restored',
      },
    ],
    summaryNote: 'Bác Ba bị cảm nặng một mình trong đêm mưa. Bát cháo gà ấm áp của bạn đã cứu nguy người tổ trưởng kính yêu.',
  },
  {
    id: 'tho_cam_ep_04',
    characterId: 'tho_cam',
    characterName: 'Bé Thỏ Cam',
    characterRole: 'Người Mặc Đồ Thú Bông Phát Tờ Rơi',
    avatar: ASSETS.thocam.front,
    episodeIndex: 4,
    title: 'Tập 4: Mảnh Giấy Note Thứ Tư & Bàn Số 2',
    subtitle: 'Mimi dõi theo chuyện tình thanh xuân của Na và Dũng',
    unlockDay: 22,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'tho_cam_ep_03',
    narrativeIntro: `Tiệm mới có hoa giấy nở rực rỡ, Thỏ Cam ghé quán sau ca làm việc buổi trưa. Trên quầy xuất hiện bức thư tay thứ tư được vẽ thêm hình hai cô cậu học trò đang chia nhau miếng gà rán.`,
    dialogueLines: [
      {
        speaker: 'Thư Thỏ Cam',
        text: '"Bàn số 2 hôm nay đẹp lắm anh ơi... Bạn nam vẽ tặng bạn nữ một bức tranh hoa giấy, bạn nữ cười rạng rỡ như ánh mặt trời..."',
        mood: 'happy',
      },
      {
        speaker: 'Thư Thỏ Cam',
        text: '"Em cũng ước một ngày nào đó được ngồi ăn đàng hoàng như vậy, không phải trốn sau bộ đồ bông nóng nực này nữa..."',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Thấy Mimi ước ao có được cảm giác ngồi thưởng thức bữa ăn bình dị, bạn làm gì?',
    choices: [
      {
        id: 'tho_cam_04_invite_sit',
        label: 'Kéo chiếc ghế bàn cạnh hoa giấy: "Cởi mũ thỏ ra ngồi đây ăn cùng anh, ở đây em là khách quý nhất!"',
        kicker: '🌸 CHỖ NGỒI DANH DỰ',
        reactionDialogue: 'Mimi e thẹn tháo chiếc đầu thỏ, để lộ gương mặt mồ hôi nhễ nhại nhưng đôi mắt lấp lánh nụ cười thiên thần: "Em cảm ơn anh... Gà rán ở đây ngon nhất quả đất!"',
        causalityNotice: 'Mimi cởi bỏ sự tự ti! Mối quan hệ trở nên gắn bó như người một nhà.',
        karmaEffect: { community: 20, craftsmanship: 10 },
        setsFlag: 'mimi_sit_in_shop',
      },
    ],
    summaryNote: 'Thỏ Cam để lại bức thư thứ tư ghi lại chuyện tình bàn số 2. Bạn kéo ghế mời cô bé ngồi ăn đàng hoàng dưới giàn hoa giấy.',
  },
  {
    id: 'tho_cam_ep_05',
    characterId: 'tho_cam',
    characterName: 'Bé Thỏ Cam',
    characterRole: 'Người Mặc Đồ Thú Bông Phát Tờ Rơi',
    avatar: ASSETS.thocam.front,
    episodeIndex: 5,
    title: 'Tập 5: Học Bổng Thiết Kế & Hộp Bánh Su Kem',
    subtitle: 'Bước tiến đầu tiên trên con đường tìm lại chính mình',
    unlockDay: 42,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'tho_cam_ep_04',
    narrativeIntro: `Mimi đến tiệm mà không mặc bộ đồ mascot! Cô bé diện chiếc váy hoa nhí giản dị, tay ôm hộp bánh su kem Chợ Lớn thơm lừng nụ cười rạng rỡ không giấu nổi niềm vui sướng.`,
    dialogueLines: [
      {
        speaker: 'Mimi',
        text: 'Anh chủ ơi! Em đỗ vòng phỏng vấn thiết kế đồ họa của công ty truyền thông rồi! Từ tháng sau em không phải đi phát tờ rơi ngoài ngã tư nữa!',
        mood: 'happy',
      },
      {
        speaker: 'Mimi',
        text: 'Em mua hộp su kem gia truyền mừng anh và tiệm gà. Nhờ những bữa gà rán và lời động viên của anh mà em có đủ dũng khí đi nộp hồ sơ đó!',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Mimi đạt được bước ngoặt lớn đầu đời! Bạn cùng cô bé ăn mừng thế nào?',
    choices: [
      {
        id: 'tho_cam_05_party_feast',
        label: 'Chiên ngay mẹt cánh gà sốt cay bơ tỏi đặc biệt đãi tiệc mừng Mimi',
        kicker: '🎉 ĐẠI TIỆC MỪNG CHIẾN THẮNG',
        reactionDialogue: 'Mimi vừa ăn vừa cười tít mắt: "Sau này công ty có dự án lớn, em nhất định sẽ thiết kế poster miễn phí cho quán của anh!"',
        causalityNotice: 'Mở khóa nhánh Mimi hỗ trợ thiết kế truyền thông thương hiệu ở các chương sau.',
        karmaEffect: { community: 25, ambition: 15 },
        setsFlag: 'mimi_designer_allied',
      },
    ],
    summaryNote: 'Mimi đỗ học bổng thiết kế đồ họa, từ giã nghề phát tờ rơi. Tình thân giữa Mimi và tiệm gà bước sang trang mới tươi sáng.',
  },
  {
    id: 'na_ep_04',
    characterId: 'le_bao_na',
    characterName: 'Em Na',
    characterRole: 'Nữ Sinh Trường Múa',
    avatar: ASSETS.hocsinh.stand,
    episodeIndex: 4,
    title: 'Tập 4: Đôi Giày Múa Khắc Hình Cánh Gà',
    subtitle: 'Món quà tiếp sức độc nhất vô nhị từ cậu bạn thân Dũng',
    unlockDay: 25,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'na_ep_03',
    narrativeIntro: `Na và Dũng ngồi ở bàn số 2 quen thuộc. Dũng vừa cặm cụi dùng cọ vẽ acrylic vẽ lên đôi giày múa lụa trắng của Na hình ngọn lửa và đôi cánh gà cách điệu vàng óng. Na ngắm nghía đôi giày với vẻ thích thú tột cùng.`,
    dialogueLines: [
      {
        speaker: 'Em Na',
        text: 'Dũng vẽ khéo ghê chưa! Nhìn như đôi cánh đang bay vậy đó anh chủ!',
        mood: 'happy',
      },
      {
        speaker: 'Dũng',
        text: 'Cậu mang đôi giày này đi thi bán kết toàn quốc, đảm bảo ban giám khảo chấm điểm 10 bay bổng!',
        mood: 'happy',
      },
    ],
    dilemmaPrompt: 'Thấy đôi bạn trẻ khăng khít và đầy nhiệt huyết, bạn gửi lời chúc gì tới Na?',
    choices: [
      {
        id: 'na_04_bless_wings',
        label: 'Tặng Na một phần gà chiên giòn lấy may: "Hãy bay thật cao trên sân khấu nhé Na!"',
        kicker: '✨ ĐÔI CÁNH VÀNG',
        reactionDialogue: 'Na nắm chặt tay Dũng, cười tươi rói: "Có anh chủ và Dũng cổ vũ, em tự tin 100% luôn!"',
        causalityNotice: 'Na bước vào vòng bán kết với tâm lý thép! Khả năng đoạt giải cao.',
        karmaEffect: { community: 15, craftsmanship: 15 },
        setsFlag: 'na_wings_blessed',
      },
    ],
    summaryNote: 'Dũng vẽ trang trí đôi giày múa cho Na với biểu tượng đôi cánh gà tiệm. Na vững tin bước vào kỳ thi quốc gia.',
  },
  {
    id: 'dung_ep_03',
    characterId: 'tran_dung',
    characterName: 'Dũng Vẽ Truyện',
    characterRole: 'Họa Sĩ Truyện Tranh Đam Mê',
    avatar: ASSETS.hocsinh.stand,
    episodeIndex: 3,
    title: 'Tập 3: Bức Chân Dung Bí Mật Trong Cặp Sách',
    subtitle: 'Tâm sự tuổi 18 của cậu bạn bàn bên',
    unlockDay: 28,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'dung_ep_02',
    narrativeIntro: `Khi Na về trước, Dũng nấn ná ở lại quầy. Cậu ngập ngừng mở chiếc cặp sờn góc, rút ra một tập tranh vẽ màu nước tuyệt đẹp: toàn bộ là những khoảnh khắc Na đang múa, đang cười, đang ăn gà rán tại quán.`,
    dialogueLines: [
      {
        speaker: 'Dũng',
        text: 'Anh chủ... em thích Na từ hồi lớp 10 lận. Nhưng Na sáng chói quá, còn em chỉ là thằng vẽ truyện nghèo...',
        mood: 'sad',
      },
      {
        speaker: 'Dũng',
        text: 'Em sợ nếu nói ra, tụi em tới làm bạn cũng không làm được nữa...',
        mood: 'tense',
      },
    ],
    dilemmaPrompt: 'Cậu em trai tuổi mới lớn thổ lộ chuyện thầm thương trộm nhớ. Lời khuyên của bạn là gì?',
    choices: [
      {
        id: 'dung_03_encourage_confess',
        label: 'Khuyên Dũng dùng chính những trang truyện này để bày tỏ tình cảm chân thành với Na',
        kicker: '💌 TÌNH CẢM CHÂN THÀNH',
        reactionDialogue: 'Dũng đỏ bừng mặt nhưng gật đầu dứt khoát: "Dạ! Đợi Na thi xong, em sẽ gom hết can đảm tặng Na cuốn truyện này!"',
        causalityNotice: 'Kích hoạt tuyến tình cảm ngọt ngào giữa Dũng và Na ở các chương sau.',
        karmaEffect: { community: 20, ambition: 10 },
        setsFlag: 'dung_confession_planned',
      },
    ],
    summaryNote: 'Dũng hé lộ bức tranh chân dung vẽ Na giấu kín trong cặp sách. Bạn tiếp thêm dũng khí cho tình yêu trong sáng tuổi học trò.',
  },
  {
    id: 'anh_long_ep_03',
    characterId: 'anh_long',
    characterName: 'Anh Long Trưởng Phòng',
    characterRole: 'Trưởng Phòng IT & Anh Trai Na',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 3,
    title: 'Tập 3: Đơn Hàng Bucket 40 Người Khao Công Ty',
    subtitle: 'Sự ủng hộ thầm lặng của người đàn ông nguyên tắc',
    unlockDay: 30,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'anh_long_ep_02',
    narrativeIntro: `Trưa thứ Sáu, điện thoại quán rung lên liên hồi. Anh Long gọi đến với giọng hào sảng: "Alo chú em! Team IT của anh vừa release xong dự án lớn, anh muốn đặt 40 combo bucket gà cay và khoai lắc khao cả phòng!".`,
    dialogueLines: [
      {
        speaker: 'Anh Long',
        text: 'Mấy đứa công ty anh suốt ngày ăn gà công nghiệp ngấy mỡ. Hôm nay anh cho tụi nó nếm thử gà chuẩn vị hẻm 1102 xem ai đỉnh hơn!',
        mood: 'happy',
      },
      {
        speaker: 'Bạn (Chủ Quán)',
        text: 'Dạ anh Long! Em sẽ chuẩn bị nóng hổi giao đúng 11h45 cho kịp giờ ăn trưa của các anh!',
        mood: 'happy',
      },
    ],
    dilemmaPrompt: 'Đơn hàng công ty đầu tiên lên tới 40 phần! Bạn chiên và đóng gói thế nào để giữ trọn chất lượng?',
    choices: [
      {
        id: 'long_03_perfect_prep',
        label: 'Chiên theo từng đợt nhỏ, dùng hộp giữ nhiệt lót giấy thấm dầu và tặng kèm 5 chai tương sốt bí truyền',
        kicker: '📦 TIÊU CHUẨN ĐẠI TIỆC',
        reactionDialogue: 'Chiều hôm đó anh Long nhắn tin: "Cả công ty khen nức nở! Sếp anh còn hỏi địa chỉ để tuần sau đặt tiếp liên hoan!"',
        causalityNotice: 'Doanh thu bùng nổ! Mở khóa tệp khách hàng văn phòng trung thành đặt bucket số lượng lớn.',
        karmaEffect: { craftsmanship: 20, ambition: 20 },
        rewardMoney: 800000,
        setsFlag: 'corporate_clients_unlocked',
      },
    ],
    summaryNote: 'Anh Long đặt 40 phần gà khao công ty IT. Tiệm ghi điểm tuyệt đối trong mắt giới văn phòng công nghệ.',
  },
  {
    id: 'mai_ep_03',
    characterId: 'chi_mai',
    characterName: 'Chị Mai Kế Toán',
    characterRole: 'Kế Toán Mẹ Đơn Thân',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 3,
    title: 'Tập 3: Bé Bắp Đạt Điểm 10 Vở Sạch Chữ Đẹp',
    subtitle: 'Bữa tiệc nhỏ ăn mừng thành quả của cô bé bàn số 1',
    unlockDay: 24,
    unlockChapter: 2,
    prerequisiteEpisodeId: 'mai_ep_02',
    narrativeIntro: `Bé Bắp chạy ùa vào tiệm, hai bím tóc lắc lư khoe quyển vở tập viết đỏ chót điểm 10. Chị Mai đi phía sau, nụ cười rạng rỡ xóa tan đi nét mệt mỏi thường ngày trên gương mặt người mẹ đơn thân.`,
    dialogueLines: [
      {
        speaker: 'Bé Bắp',
        text: 'Chú chủ tiệm ơi! Cô giáo chấm con viết chữ đẹp nhất lớp luôn nè chú! Nhờ tối nào con cũng ngồi bàn số 1 nắn nót viết bài đó!',
        mood: 'happy',
      },
      {
        speaker: 'Chị Mai',
        text: 'Hôm nay mẹ cho Bắp ăn thỏa thích đùi gà sốt mật ong nha!',
        mood: 'happy',
      },
    ],
    dilemmaPrompt: 'Mừng thành tích của cô bé chăm ngoan của hẻm, bạn chúc mừng thế nào?',
    choices: [
      {
        id: 'mai_03_treat_bap',
        label: 'Tặng bé Bắp chiếc đùi gà khổng lồ cùng ly nước ngọt cắm ống hút trái tim',
        kicker: '⭐ PHẦN THƯỞNG HOA ĐIỂM 10',
        reactionDialogue: 'Bé Bắp ôm chầm lấy bạn: "Con cảm ơn chú! Lớn lên con cũng sẽ làm cô giáo dạy chữ cho các bạn nghèo!"',
        causalityNotice: 'Tình cảm gia đình gắn kết keo sơn. Chị Mai quyết định nhận giúp tiệm làm báo cáo thuế.',
        karmaEffect: { community: 20 },
        setsFlag: 'bap_rewarded_study',
      },
    ],
    summaryNote: 'Bé Bắp đạt điểm 10 vở sạch chữ đẹp tại bàn số 1. Tiệm gà trở thành ngôi nhà thứ hai đầy ắp yêu thương của hai mẹ con.',
  },

  // =========================================================================
  // CHƯƠNG 3: MẶT TIỀN PHỐ (NGÀY 51 – 100) — QUY MÔ LỚN & ĐỐI MẶT SÓNG GIÓ
  // =========================================================================
  {
    id: 'bac_ba_ep_06',
    characterId: 'bac_ba',
    characterName: 'Bác Ba Tổ Trưởng',
    characterRole: 'Cựu Bếp Trưởng Gà Chợ Lớn 1990',
    avatar: ASSETS.bacba.front,
    episodeIndex: 6,
    title: 'Tập 6: Lửa Lớn Gió To — Bước Ra Mặt Tiền Phố',
    subtitle: 'Lời răn dạy khi cửa hàng bước ra đại lộ lớn',
    unlockDay: 55,
    unlockChapter: 3,
    prerequisiteEpisodeId: 'bac_ba_ep_05',
    narrativeIntro: `Tiệm gà chính thức mở rộng ra mặt tiền đường lớn với 12 bàn khang trang, bảng đèn neon rực rỡ thu hút hàng trăm lượt khách mỗi ngày. Bác Ba đứng bên vỉa hè nhìn dòng xe cộ tấp nập, chép miệng dặn dò từng lời gan ruột.`,
    dialogueLines: [
      {
        speaker: 'Bác Ba',
        text: 'Ra mặt tiền đường lớn là mày bước vào cuộc chơi lớn rồi. Lửa càng to thì gió thổi càng dữ dội.',
        mood: 'tense',
      },
      {
        speaker: 'Bác Ba',
        text: 'Nhiều người có tiền tỷ trong tay là quên mất hương vị lúc đứng chiên vỉa hè, bắt đầu mua thịt ôi, dầu đen để ăn dày. Mày tuyệt đối không được giẫm vào vết xe đổ đó nghe chưa!',
        mood: 'normal',
      },
    ],
    dilemmaPrompt: 'Lời cảnh tỉnh đanh thép của bậc tiền bối giữa lúc tiệm đang thăng hoa. Bạn đáp từ thế nào?',
    choices: [
      {
        id: 'bac_ba_06_sacred_promise',
        label: 'Đặt tay lên ngực thề: "Dù mở 1 tiệm hay 100 tiệm, giọt dầu và thớ thịt vẫn phải tinh khiết nhất!"',
        kicker: '🛡️ GIỮ TRỌN CĂN CƠ',
        reactionDialogue: 'Bác Ba vỗ đùi đánh đét: "Tốt! Có lời này của mày thì bác mới yên tâm giao nốt những trang cuối cuốn sổ!"',
        causalityNotice: 'Khóa chặt phẩm hạnh làm nghề! Miễn nhiễm với cám dỗ giảm chất lượng để tối ưu lợi nhuận.',
        karmaEffect: { craftsmanship: 30, community: 15 },
        rewardReputation: 30,
        setsFlag: 'integrity_unshakable',
      },
    ],
    summaryNote: 'Bước ra mặt tiền phố lớn, Bác Ba cảnh báo hiểm họa của sự tự mãn. Bạn thề giữ vững đạo đức nghề bếp.',
  },
  {
    id: 'na_ep_06',
    characterId: 'le_bao_na',
    characterName: 'Em Na',
    characterRole: 'Nữ Sinh Trường Múa',
    avatar: ASSETS.hocsinh.stand,
    episodeIndex: 6,
    title: 'Tập 6: Khán Đài Đêm Bán Kết & Cái Ôm Của Anh Long',
    subtitle: 'Bức tường ngăn cách gia đình sụp đổ trong nước mắt',
    unlockDay: 68,
    unlockChapter: 3,
    prerequisiteEpisodeId: 'na_ep_05',
    narrativeIntro: `Đêm bán kết cuộc thi Múa Đương Đại Toàn Quốc tại Nhà hát Thành Phố. Na bước ra sân khấu trong tiếng nhạc du dương. Ở hàng ghế khán giả, một bóng người đàn ông mặc vest chỉnh tề – chính là Anh Long, đang run run cầm bó hoa hồng giấu sau lưng.`,
    dialogueLines: [
      {
        speaker: 'Anh Long (Nói với bạn đi cùng)',
        text: 'Tôi tưởng con bé chỉ nhảy múa con nít... Không ngờ trên sân khấu nó tỏa sáng lộng lẫy đến thế này chú em à...',
        mood: 'touched',
      },
      {
        speaker: 'Em Na (Khi bước xuống nhận hoa)',
        text: 'Anh hai... Em tưởng anh không tới...',
        mood: 'sad',
      },
      {
        speaker: 'Anh Long',
        text: 'Anh hai sai rồi Na ơi... Từ nay anh sẽ là khán giả trung thành nhất của em!',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Hai anh em ôm nhau khóc nức nở trong hậu trường sau bao năm mâu thuẫn. Bạn làm gì để lưu giữ khoảnh khắc này?',
    choices: [
      {
        id: 'na_06_celebrate_family',
        label: 'Dùng máy ảnh chụp lại cái ôm lịch sử của hai anh em, mời cả gia đình về tiệm mở tiệc mừng Na vào chung kết',
        kicker: '📸 KHOẢNH KHẮC ĐOÀN TỤ',
        reactionDialogue: 'Tấm ảnh đoàn tụ được lồng khung gỗ trang trọng treo ở vị trí đẹp nhất trong tiệm gà, lan tỏa sự ấm áp cho mọi thực khách.',
        causalityNotice: 'Hàn gắn trọn vẹn gia đình Long & Na! Mở khóa sự kiện Na sáng tác vũ điệu độc quyền cho tiệm.',
        karmaEffect: { community: 35, craftsmanship: 20 },
        setsFlag: 'long_na_fully_reconciled',
      },
    ],
    summaryNote: 'Anh Long bí mật đến nhà hát xem Na múa và xin lỗi em gái. Tình thân máu mủ hàn gắn trọn vẹn tại tiệm gà.',
  },
  {
    id: 'anh_long_ep_04',
    characterId: 'anh_long',
    characterName: 'Anh Long Trưởng Phòng',
    characterRole: 'Trưởng Phòng IT & Anh Trai Na',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 4,
    title: 'Tập 4: Lá Đơn Xin Thôi Việc & Giấc Mơ Khởi Nghiệp F&B',
    subtitle: 'Khi người làm thuê quyết định bứt phá làm chủ cuộc đời',
    unlockDay: 75,
    unlockChapter: 3,
    prerequisiteEpisodeId: 'anh_long_ep_03',
    narrativeIntro: `Anh Long ghé tiệm với nụ cười nhẹ bẫng kỳ lạ. Anh đặt lên bàn một lá đơn xin thôi việc đã được giám đốc ký duyệt. Sau 10 năm cày cuốc đến loét dạ dày cho các tập đoàn nước ngoài, anh quyết định rẽ hướng.`,
    dialogueLines: [
      {
        speaker: 'Anh Long',
        text: 'Anh nộp đơn rồi chú em. Anh chán cảnh làm giàu cho tư bản ngoại quốc để rồi bị sa thải bất cứ lúc nào.',
        mood: 'happy',
      },
      {
        speaker: 'Anh Long',
        text: 'Anh muốn dùng chuyên môn IT của mình viết một hệ thống quản lý chuỗi và app đặt món riêng cho tiệm gà của chú em. Mình tự làm chủ, tự quyết định vận mệnh!',
        mood: 'happy',
      },
    ],
    dilemmaPrompt: 'Anh Long ngỏ ý bắt tay hợp tác phát triển nền tảng công nghệ cho quán. Bạn phản hồi thế nào?',
    choices: [
      {
        id: 'long_04_partner_tech',
        label: 'Bắt chặt tay anh Long: "Chào mừng Giám đốc Công nghệ của Tiệm Gà Nhà Tui!"',
        kicker: '💻 LIÊN MINH CÔNG NGHỆ',
        reactionDialogue: 'Anh Long cười vang, đôi mắt rực sáng đam mê: "Ok! Anh cam kết app của tiệm mình sẽ mượt hơn cả Grab lẫn ShopeeFood!"',
        causalityNotice: 'Mở khóa nhánh phát triển Ứng Dụng Độc Quyền (Own App) không mất 30% phí sàn.',
        karmaEffect: { ambition: 30, craftsmanship: 20 },
        rewardMoney: 1500000,
        setsFlag: 'long_cto_partnership',
      },
    ],
    summaryNote: 'Anh Long nghỉ việc công sở, bắt tay hợp tác cùng bạn xây dựng hệ thống công nghệ đặt món độc quyền cho chuỗi tiệm gà.',
  },
  {
    id: 'mai_ep_05',
    characterId: 'chi_mai',
    characterName: 'Chị Mai Kế Toán',
    characterRole: 'Kế Toán Mẹ Đơn Thân',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 5,
    title: 'Tập 5: Chiếc Nhẫn Bạc & Lời Cầu Hôn Của Tuấn Shipper',
    subtitle: 'Hạnh phúc đơm hoa kết trái sau những năm tháng nhọc nhằn',
    unlockDay: 82,
    unlockChapter: 3,
    prerequisiteEpisodeId: 'mai_ep_03',
    narrativeIntro: `Đêm Trung Thu, quán lung linh ánh đèn lồng giấy kính. Tuấn shipper trong chiếc áo sơ mi trắng hiếm hoi, lúng túng rút ra chiếc hộp nhung đỏ trước mặt chị Mai và bé Bắp tại bàn số 1.`,
    dialogueLines: [
      {
        speaker: 'Anh Tuấn',
        text: 'Mai à... Anh mồ côi từ nhỏ, chạy xe ôm kiếm từng đồng... Nhưng anh thề cả đời này sẽ che chở cho hai mẹ con em, không để em phải khóc nữa.',
        mood: 'touched',
      },
      {
        speaker: 'Bé Bắp',
        text: 'Mẹ ơi mẹ đồng ý đi! Con muốn chú Tuấn làm Ba của con!',
        mood: 'happy',
      },
      {
        speaker: 'Chị Mai',
        text: 'Tuấn... Em đồng ý...',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Khoảnh khắc thiêng liêng nhất đời người diễn ra ngay tại tiệm gà của bạn. Bạn chúc phúc cho đôi uyên ương ra sao?',
    choices: [
      {
        id: 'mai_05_wedding_blessing',
        label: 'Bật bài hát rộn ràng, tặng hai người cặp nhẫn cưới bạc và nhận lo toàn bộ tiệc cưới tại tiệm',
        kicker: '💍 HẠNH PHÚC VIÊN MÃN',
        reactionDialogue: 'Cả quán vỗ tay reo hò rầm rộ, bà con hàng xóm ùa vào chúc mừng. Nước mắt hạnh phúc lăn dài trên má chị Mai.',
        causalityNotice: 'Hẻm 1102 đón tin vui lớn! Tuấn chính thức trở thành Đội trưởng vận tải độc quyền của tiệm.',
        karmaEffect: { community: 40 },
        setsFlag: 'tuan_mai_married',
      },
    ],
    summaryNote: 'Tuấn shipper cầu hôn chị Mai thành công dưới sự chứng kiến của bé Bắp và cả xóm hẻm. Tiệm gà tràn ngập hỷ khí.',
  },
  {
    id: 'kinh_tron_ep_03',
    characterId: 'kinh_tron',
    characterName: 'Ông Kính Tròn',
    characterRole: 'Food Critic Ẩn Danh Của Giải Gà Vàng',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 3,
    title: 'Tập 3: Vali Tiền 2 Tỷ Của Mr. Mega',
    subtitle: 'Lời đề nghị khiếm nhã và bài thử thách danh dự sinh tử',
    unlockDay: 95,
    unlockChapter: 3,
    prerequisiteEpisodeId: 'kinh_tron_ep_01',
    narrativeIntro: `Một chiếc Mercedes đen bóng đỗ xịch trước cửa quán. Bước xuống xe là Mr. Mega (Mạc Gia Khang) – CEO tập đoàn đồ ăn nhanh MegaChicken, theo sau là hai vệ sĩ xách chiếc vali da đen. Đúng lúc đó, Ông Kính Tròn cũng lặng lẽ ngồi ở góc quán quan sát.`,
    dialogueLines: [
      {
        speaker: 'Mr. Mega',
        text: 'Chào chủ quán nhỏ. Tôi vào thẳng vấn đề: trong vali này có 2 tỷ đồng tiền mặt. Bán đứt công thức sốt và thương hiệu lại cho MegaChicken.',
        mood: 'tense',
      },
      {
        speaker: 'Mr. Mega',
        text: 'Cậu cầm 2 tỷ này tha hồ mua nhà, mua xe hơi. Còn tiệm này sẽ trở thành chi nhánh bán gà công nghiệp của tôi.',
        mood: 'tense',
      },
      {
        speaker: 'Bạn (Chủ Quán)',
        text: 'Nếu tôi từ chối thì sao?',
        mood: 'tense',
      },
      {
        speaker: 'Mr. Mega',
        text: 'Thì MegaChicken sẽ mở một đại siêu thị gà rán ngay đối diện, chi 10 tỷ khuyến mãi đè bẹp tiệm của cậu trong vòng 3 tháng!',
        mood: 'tense',
      },
    ],
    dilemmaPrompt: 'Đứng trước 2 tỷ đồng tiền mặt và lời đe dọa hủy diệt từ tập đoàn khổng lồ, bạn quyết định thế nào?',
    choices: [
      {
        id: 'mega_03_refuse_fierce',
        label: 'Đóng sập nắp vali đẩy trả lại: "Tiệm Gà Nhà Tui được xây bằng tình nghĩa xóm hẻm, không có giá để bán!"',
        kicker: '⚔️ TUYÊN CHIẾN ĐỐI THỦ',
        reactionDialogue: 'Mr. Mega tím mặt giận dữ giật lấy vali: "Cậu sẽ phải hối hận vì sự ngây thơ này!" Ở góc quán, Ông Kính Tròn khẽ mỉm cười nâng ly trà tán thưởng bản lĩnh của bạn.',
        causalityNotice: 'Chính thức bước vào Cuộc Chiến Chuỗi Gà Rán ở Chương 4! Mở khóa con đường Di Sản Bất Tử.',
        karmaEffect: { craftsmanship: 40, community: 30, ambition: -20 },
        rewardReputation: 50,
        setsFlag: 'mega_hostility_declared',
      },
      {
        id: 'mega_03_bargain_smart',
        label: 'Cười khẩy: "2 tỷ quá rẻ mạt cho công thức gia truyền 30 năm. Hãy đợi đến giải Gà Vàng rồi nói chuyện thị phần!"',
        kicker: '🏆 THÁCH ĐẤU ĐỈNH CAO',
        reactionDialogue: 'Mr. Mega gằn giọng: "Được lắm! Để xem chiếc chảo gang cổ lỗ sĩ của cậu đấu lại dây chuyền tự động hóa của tôi thế nào!"',
        causalityNotice: 'Khởi động cuộc đọ sức tại Giải Gà Vàng Quốc Gia! Điểm Ambition tăng vọt.',
        karmaEffect: { ambition: 40, craftsmanship: 20 },
        rewardReputation: 40,
        setsFlag: 'mega_challenge_accepted',
      },
    ],
    summaryNote: 'Mr. Mega mang vali 2 tỷ đồng ép mua lại công thức. Bạn thẳng thừng từ chối, chính thức tuyên chiến với đế chế đồ ăn nhanh.',
  },

  // =========================================================================
  // CHƯƠNG 4: TIỆM HOT TREND & CUỘC CHIẾN CHUỖI (NGÀY 101 – 150)
  // =========================================================================
  {
    id: 'bac_ba_ep_07',
    characterId: 'bac_ba',
    characterName: 'Bác Ba Tổ Trưởng',
    characterRole: 'Cựu Bếp Trưởng Gà Chợ Lớn 1990',
    avatar: ASSETS.bacba.front,
    episodeIndex: 7,
    title: 'Tập 7: Cú Lừa Năm 1990 & Kẻ Thù Ba Mươi Năm',
    subtitle: 'Sự thật chấn động về cái chết của cụ Võ Hòa',
    unlockDay: 110,
    unlockChapter: 4,
    prerequisiteEpisodeId: 'bac_ba_ep_06',
    narrativeIntro: `Đêm khuya sau khi Mr. Mega cho người rải tờ rơi bôi nhọ quán, Bác Ba ngồi lặng lẽ bên tách trà đặc. Ánh mắt già nua ánh lên nỗi đau đớn kìm nén suốt ba thập kỷ.`,
    dialogueLines: [
      {
        speaker: 'Bác Ba',
        text: 'Năm 1990, cha của Mạc Gia Khang cũng dùng đúng chiêu này: cài người đổ thuốc sâu vào kho bột của tiệm Chợ Lớn rồi báo công an...',
        mood: 'sad',
      },
      {
        speaker: 'Bác Ba',
        text: 'Thầy Võ Hòa uất ức mà đột quỵ qua đời. Ba mươi năm sau, con trai ông ta lại muốn dùng tiền dẫm nát con cháu người Chợ Lớn một lần nữa!',
        mood: 'tense',
      },
      {
        speaker: 'Bác Ba',
        text: 'Lần này có cả xóm hẻm đứng sau lưng, bác cháu mình quyết không lùi một bước!',
        mood: 'tense',
      },
    ],
    dilemmaPrompt: 'Biết được ân oán truyền kiếp giữa hai thế hệ, bạn lên kế hoạch đáp trả thế nào?',
    choices: [
      {
        id: 'bac_ba_07_open_kitchen',
        label: 'Tổ chức ngày hội "Bếp Mở Minh Bạch": Mời truyền hình và thực khách trực tiếp vào bếp xem dầu sạch và nguyên liệu',
        kicker: '🔍 BẾP MỞ MINH BẠCH',
        reactionDialogue: 'Bác Ba đập tay xuống bàn: "Kế hay! Sự thật là tấm khiên vững chắc nhất, đập tan mọi chiêu trò vu khống!"',
        causalityNotice: 'Hàng ngàn khách hàng kéo đến kiểm chứng và ca ngợi độ sạch chuẩn 5 sao của tiệm!',
        karmaEffect: { craftsmanship: 35, community: 25 },
        rewardReputation: 45,
        setsFlag: 'open_kitchen_success',
      },
    ],
    summaryNote: 'Bác Ba hé lộ ân oán năm 1990 giữa cụ Võ Hòa và cha con Mr. Mega. Tiệm mở chiến dịch Bếp Minh Bạch đập tan âm mưu bẩn.',
  },
  {
    id: 'tho_cam_ep_07',
    characterId: 'tho_cam',
    characterName: 'Bé Thỏ Cam',
    characterRole: 'Người Mặc Đồ Thú Bông Phát Tờ Rơi',
    avatar: ASSETS.thocam.front,
    episodeIndex: 7,
    title: 'Tập 7: Giọt Nước Mắt Dưới Bộ Đồ Thỏ Cam',
    subtitle: 'Mimi bị MegaChicken ép chặn cửa phá tiệm bạn',
    unlockDay: 118,
    unlockChapter: 4,
    prerequisiteEpisodeId: 'tho_cam_ep_05',
    narrativeIntro: `Một buổi sáng náo loạn, trước cửa tiệm xuất hiện một nhóm mascot thỏ cam cầm biển giảm giá 70% của MegaChicken chặn ngay đầu hẻm. Trong số đó, có một chú thỏ đứng run rẩy, nước mắt chảy ròng ròng ướt đẫm lớp vải bông bên trong. Đó chính là Mimi.`,
    dialogueLines: [
      {
        speaker: 'Mimi (Khóc nấc trong bộ đồ thỏ)',
        text: 'Anh chủ ơi... Công ty truyền thông của em bị MegaChicken mua lại rồi... Họ dọa nếu em không đứng đây phát voucher phá anh thì họ sẽ kiện em đền 200 triệu tiền phá vỡ hợp đồng...',
        mood: 'sad',
      },
      {
        speaker: 'Mimi',
        text: 'Em thà chết chứ không muốn hại tiệm của anh và ông ngoại...',
        mood: 'sad',
      },
    ],
    dilemmaPrompt: 'Thấy cô bé bị dồn vào bước đường cùng tàn nhẫn, bạn hành động thế nào?',
    choices: [
      {
        id: 'tho_cam_07_rescue_mimi',
        label: 'Kéo Mimi vào quán, xé phăng tờ voucher của MegaChicken và tuyên bố: "Tiệm Gà Nhà Tui sẽ trả tiền đền hợp đồng và nhận em về làm việc ngay hôm nay!"',
        kicker: '🛡️ GIẢI CỨU THỎ CAM',
        reactionDialogue: 'Mimi vỡ òa ôm chầm lấy bạn khóc nức nở. Toàn bộ cư dân Hẻm 1102 lập tức ùa ra xua đuổi đám nhân viên khiêu khích của MegaChicken!',
        causalityNotice: 'Mimi chính thức gia nhập Tiệm Gà Nhà Tui! Toàn bộ mưu hèn kế bẩn của đối thủ bị lật tẩy trên mạng xã hội.',
        karmaEffect: { community: 50, craftsmanship: 20, ambition: -15 },
        setsFlag: 'mimi_rescued_full',
      },
    ],
    summaryNote: 'Mimi bị MegaChicken ép đi phát voucher phá tiệm bạn. Bạn đứng ra che chở đền hợp đồng, giải thoát cô bé khỏi nanh vuốt kẻ xấu.',
  },
  {
    id: 'duc_huy_ep_03',
    characterId: 'duc_huy',
    characterName: 'Đức Huy Game Thủ',
    characterRole: 'Cú Đêm IT & Chuyên Viên An Ninh Mạng',
    avatar: ASSETS.gamethu.stand,
    episodeIndex: 3,
    title: 'Tập 3: Cuộc Tấn Công DDoS 12 Giờ Trưa',
    subtitle: 'Đức Huy trắng đêm giữ vững phòng tuyến công nghệ',
    unlockDay: 135,
    unlockChapter: 4,
    prerequisiteEpisodeId: 'duc_huy_ep_01',
    narrativeIntro: `Đúng 11h45 trưa ngày rằm, khi hàng trăm đơn app đổ về dồn dập, toàn bộ hệ thống đặt món và đường truyền mạng của quán bỗng nhiên tê liệt. Đức Huy ôm laptop lao thẳng vào bếp, vẻ mặt lạnh lùng như một chỉ huy trận chiến.`,
    dialogueLines: [
      {
        speaker: 'Đức Huy',
        text: 'Họ dùng mạng botnet từ 10.000 máy chủ ảo bắn phá băng thông tiệm mình! Mục đích là làm nghẽn đơn để khách hủy hàng và đánh giá 1 sao!',
        mood: 'tense',
      },
      {
        speaker: 'Đức Huy',
        text: 'Cho em 15 phút và 2 miếng gà nóng! Em sẽ chuyển hướng toàn bộ luồng tấn công ngược về máy chủ chính của MegaChicken!',
        mood: 'happy',
      },
    ],
    dilemmaPrompt: 'Trận chiến an ninh mạng nghẹt thở giữa giờ cao điểm. Bạn tiếp sức cho Huy thế nào?',
    choices: [
      {
        id: 'duc_huy_03_counter_strike',
        label: 'Đặt lên bàn đĩa gà chiên giòn cay rực lửa và ly cà phê sữa đá đậm đặc: "Toàn bộ niềm tin của tiệm đặt vào em!"',
        kicker: '💻 PHẢN CÔNG MẠNG',
        reactionDialogue: 'Đôi tay Huy lướt trên bàn phím như nghệ sĩ dương cầm. 10 phút sau, hệ thống thông suốt, máy chủ MegaChicken sập nguồn tê liệt!',
        causalityNotice: 'Huy bảo vệ hoàn hảo hệ thống đặt đơn! Bắt thóp chứng cứ nộp lên Cục An Ninh Mạng.',
        karmaEffect: { craftsmanship: 30, ambition: 20 },
        rewardReputation: 40,
        setsFlag: 'mega_ddos_crushed',
      },
    ],
    summaryNote: 'Đức Huy đập tan cuộc tấn công DDoS quy mô lớn của MegaChicken, khẳng định sức mạnh công nghệ vượt trội của tiệm gà.',
  },

  // =========================================================================
  // CHƯƠNG 5: CHUỖI GÀ QUỐC DÂN & ĐẠI KẾT CỤC (NGÀY 151 – 210+)
  // =========================================================================
  {
    id: 'tho_cam_ep_08',
    characterId: 'tho_cam',
    characterName: 'Bé Thỏ Cam',
    characterRole: 'Người Mặc Đồ Thú Bông Phát Tờ Rơi',
    avatar: ASSETS.thocam.front,
    episodeIndex: 8,
    title: 'Tập 8: Mở Lại Biển Hiệu Gà Chợ Lớn 1990',
    subtitle: 'Ước nguyện ba mươi năm của người đã khuất thành hiện thực',
    unlockDay: 180,
    unlockChapter: 5,
    prerequisiteEpisodeId: 'tho_cam_ep_07',
    narrativeIntro: `Trước căn nhà cổ số 88 đường Hải Thượng Lãn Ông (Quận 5), tấm vải đỏ phủ biển hiệu được kéo xuống. Tấm biển gỗ sơn son thiếp vàng "GÀ CHỢ LỚN — CHI NHÁNH 5 TIỆM GÀ NHÀ TUI" sáng bừng dưới nắng sớm. Mimi mặc chiếc áo dài cam truyền thống, đôi mắt ngấn lệ ôm di ảnh ông ngoại.`,
    dialogueLines: [
      {
        speaker: 'Mimi',
        text: 'Ông ngoại ơi... Bếp gà của ông mở lại rồi... Cháu gái của ông nay đã là Giám đốc chi nhánh rồi ông ơi...',
        mood: 'touched',
      },
      {
        speaker: 'Bác Ba',
        text: 'Ba mươi năm... Bác Ba chờ ngày này ba mươi năm rồi... Thầy Hòa ơi, tiệm gà mình sống lại rồi!',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Giây phút lịch sử làm sống lại một di sản ẩm thực Sài Gòn. Bạn trao quyền cho ai quản lý chi nhánh này?',
    choices: [
      {
        id: 'tho_cam_08_appoint_director',
        label: 'Trao chìa khóa vàng và quyết định bổ nhiệm cho Võ Minh Mi (Mimi) làm Giám đốc điều hành Chi nhánh Chợ Lớn',
        kicker: '🔑 CHỦ NHÂN ĐÍCH THỰC',
        reactionDialogue: 'Mimi cúi đầu nhận ấn nhiệm trong tiếng pháo tay rộn rã của bà con hai khu phố Chợ Lớn và Hẻm 1102.',
        causalityNotice: 'Hoàn thành tâm nguyện di sản! Chi nhánh Chợ Lớn mang lại doanh thu khổng lồ và điểm Karma tối thượng.',
        karmaEffect: { community: 50, craftsmanship: 40, ambition: 30 },
        rewardMoney: 10000000,
        setsFlag: 'heritage_branch_thriving',
      },
    ],
    summaryNote: 'Tái sinh thương hiệu Gà Chợ Lớn 1990 thành chi nhánh thứ 5. Mimi chính thức trở thành Giám đốc điều hành trong nước mắt đoàn tụ.',
  },
  {
    id: 'na_ep_07',
    characterId: 'le_bao_na',
    characterName: 'Em Na',
    characterRole: 'Nữ Sinh Trường Múa',
    avatar: ASSETS.hocsinh.stand,
    episodeIndex: 7,
    title: 'Tập 7: Lớp Học Múa Miễn Phí Cho Trẻ Em Hẻm 1102',
    subtitle: 'Ươm mầm nghệ thuật giữa những mái nhà nghèo',
    unlockDay: 190,
    unlockChapter: 5,
    prerequisiteEpisodeId: 'na_ep_06',
    narrativeIntro: `Tầng 2 của chi nhánh tiệm gà được Na và Dũng cải tạo thành một phòng tập múa gương kính sáng loáng. Tiếng nhạc cổ điển vang lên rộn rã, hàng chục em nhỏ con em các gia đình lao động trong hẻm đang say sưa uốn dẻo theo từng nhịp đếm của Na.`,
    dialogueLines: [
      {
        speaker: 'Em Na',
        text: 'Hồi xưa em suýt phải bỏ múa vì nghèo... Giờ em thành công rồi, em muốn dạy miễn phí cho các em nhỏ trong hẻm để không đứa trẻ nào bị dập tắt ước mơ nữa!',
        mood: 'happy',
      },
      {
        speaker: 'Dũng (Cầm máy ảnh)',
        text: 'Và mỗi buổi tập xong, tiệm gà sẽ tài trợ 1 đùi gà rán bổ sung đạm cho các vũ công nhí!',
        mood: 'happy',
      },
    ],
    dilemmaPrompt: 'Dự án thiện nguyện đầy ý nghĩa của Na và Dũng. Tiệm Gà Nhà Tui đóng góp thế nào?',
    choices: [
      {
        id: 'na_07_sponsor_academy',
        label: 'Tài trợ toàn bộ quỹ dinh dưỡng và học bổng trọn đời cho Học viện Múa Hẻm 1102',
        kicker: '🌟 CHẮP CÁNH TƯƠNG LAI',
        reactionDialogue: 'Các em nhỏ reo hò nhảy cẫng lên ôm lấy bạn và Na. Báo chí đăng tin rầm rộ ca ngợi mô hình "Doanh Nghiệp Vì Cộng Đồng".',
        causalityNotice: 'Điểm Karma Community đạt mức tối đa 100%! Khóa chặt kết cục có hậu nhất của game.',
        karmaEffect: { community: 50, craftsmanship: 20 },
        rewardReputation: 50,
        setsFlag: 'community_academy_founded',
      },
    ],
    summaryNote: 'Na mở lớp dạy múa miễn phí cho trẻ em nghèo trong hẻm. Tiệm gà trở thành cái nôi nuôi dưỡng ước mơ nghệ thuật cho thế hệ mai sau.',
  },
  {
    id: 'kinh_tron_ep_04',
    characterId: 'kinh_tron',
    characterName: 'Ông Kính Tròn',
    characterRole: 'Food Critic Ẩn Danh Của Giải Gà Vàng',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 4,
    title: 'Tập 4: Trận Đấu Sân Vận Động & Lời Tuyên Án Của Nghệ Thuật',
    subtitle: 'Vòng chung kết Cuộc thi Gà Rán Toàn Quốc',
    unlockDay: 205,
    unlockChapter: 5,
    prerequisiteEpisodeId: 'kinh_tron_ep_03',
    narrativeIntro: `Sân vận động Phú Thọ chật kín 10.000 khán giả và hàng chục đài truyền hình trực tiếp. Bên trái là cỗ máy chiên công nghiệp tự động 10 tầng của Mr. Mega; bên phải là chiếc chảo gang đáy dày và chiếc vá gỗ 1990 của bạn cùng Bác Ba và Mimi.`,
    dialogueLines: [
      {
        speaker: 'Mr. Mega',
        text: 'Máy móc của tôi chiên 1000 miếng gà trong 5 phút với dung sai 0.01%! Con người không có cửa đấu lại công nghệ!',
        mood: 'tense',
      },
      {
        speaker: 'Bạn (Chủ Quán)',
        text: 'Máy móc đo được nhiệt độ, nhưng không đo được tình yêu thương gửi vào từng miếng ăn cho thực khách.',
        mood: 'happy',
      },
      {
        speaker: 'Ông Kính Tròn (Chủ tịch Hội đồng Giám khảo)',
        text: 'Thời gian nếm thử bắt đầu. Hai bên dâng đĩa gà lên bục giám khảo!',
        mood: 'normal',
      },
    ],
    dilemmaPrompt: 'Giây phút sinh tử quyết định ngôi vương ẩm thực quốc gia. Miếng gà cuối cùng của bạn mang bí quyết gì?',
    choices: [
      {
        id: 'kinh_tron_04_master_fry',
        label: 'Vớt mẻ gà chiên chuẩn Perfect vàng óng mọng nước, rưới lớp sốt mật ong hoa cà phê Chợ Lớn 1990 thiêng liêng',
        kicker: '👑 TINH HOA NGHỆ NHÂN',
        reactionDialogue: 'Cả hội đồng giám khảo cắn miếng đầu tiên và chết lặng. Ông Kính Tròn tháo kính lau nước mắt: "Đây không phải là thức ăn nhanh... Đây là linh hồn của Sài Gòn ba mươi năm chắt chiu!"',
        causalityNotice: 'Toàn bộ 10.000 khán giả đứng dậy vỗ tay vang dội! Chiến thắng áp đảo 10-0 trước MegaChicken.',
        karmaEffect: { craftsmanship: 50, community: 40, ambition: 30 },
        rewardReputation: 100,
        setsFlag: 'national_champion_crowned',
      },
    ],
    summaryNote: 'Trận chung kết lịch sử tại sân vận động Phú Thọ. Hương vị thủ công và chiếc vá gỗ 1990 đã đánh bại cỗ máy công nghiệp, bước lên ngôi vô địch.',
  },
  {
    id: 'kinh_tron_ep_05',
    characterId: 'kinh_tron',
    characterName: 'Ông Kính Tròn',
    characterRole: 'Food Critic Ẩn Danh Của Giải Gà Vàng',
    avatar: ASSETS.vanphong.stand,
    episodeIndex: 5,
    title: 'Tập 5: Cúp Gà Vàng & Huyền Thoại Tiệm Gà Nhà Tui',
    subtitle: 'Đại kết cục vinh danh những người giữ lửa',
    unlockDay: 210,
    unlockChapter: 5,
    prerequisiteEpisodeId: 'kinh_tron_ep_04',
    narrativeIntro: `Pháo hoa rực sáng bầu trời Sài Gòn. Trên bục vinh quang cao nhất, chiếc cúp "Gà Rán Quốc Dân" bằng vàng khối được trao vào tay bạn. Bên cạnh bạn là Bác Ba, Mimi, Na, Dũng, anh Long, chị Mai, Tuấn, bé Bắp và cả con hẻm 1102 đang ôm nhau reo hò trong biển nước mắt tự hào.`,
    dialogueLines: [
      {
        speaker: 'Ông Kính Tròn',
        text: 'Nhân danh nền ẩm thực Việt Nam, ta trao chiếc cúp này cho Tiệm Gà Nhà Tui — nơi chứng minh rằng tình người và sự lương thiện luôn chiến thắng sự lạnh lùng của kim tiền.',
        mood: 'happy',
      },
      {
        speaker: 'Bác Ba',
        text: 'Thầy Võ Hòa ơi... Chúng con làm được rồi! Hẻm 1102 muôn năm!',
        mood: 'touched',
      },
    ],
    dilemmaPrompt: 'Đứng trên đỉnh vinh quang trước hàng triệu người, lời phát biểu lịch sử của bạn là gì?',
    choices: [
      {
        id: 'kinh_tron_05_speech_community',
        label: '"Chiếc cúp này không thuộc về riêng tôi, mà thuộc về từng người lao động nghèo trong con hẻm 1102 ấm áp!"',
        kicker: '❤️ DI SẢN BẤT TỬ',
        reactionDialogue: 'Tiếng hô vang "TIỆM GÀ NHÀ TUI!" rền vang khắp thành phố. Câu chuyện của bạn được ghi vào sử sách ẩm thực như một thiên tiểu thuyết đời sống kỳ diệu.',
        causalityNotice: 'Hoàn thành 100% Tuyến Cốt Truyện Đại Kết Cục! Mở khóa Happy Ending & Secret Ending vĩnh cửu.',
        karmaEffect: { community: 50, craftsmanship: 50, ambition: 50 },
        rewardMoney: 50000000,
        setsFlag: 'ultimate_legend_achieved',
      },
    ],
    summaryNote: 'Giành cúp Gà Vàng Quốc Dân danh giá. Thiên tiểu thuyết triệu chữ Hẻm 1102 khép lại trọn vẹn trong niềm tự hào và tình nghĩa sắt son.',
  },
];
