import { StaffMember, StaffRole, StaffRarity } from '../types/game';

export interface GachaStaffCandidate extends StaffMember {
  rarity: StaffRarity;
  stars: number;
  title: string;
  laziness: number;    // % nguy cơ chậm trễ / xao nhãng
  errorRate: number;   // % nguy cơ làm sai món / cháy / rơi vãi
  passiveName: string;
  passiveDesc: string;
  quote: string;       // Câu nói cửa miệng khi xuất hiện
}

// 72 MODEL NHÂN VIÊN GACHA (6 VAI TRÒ x 12 MODEL)
// Phân bố: 4 Common (1★), 4 Rare (2★), 3 Super Rare (3★), 1 SSR (5★)
export const GACHA_STAFF_POOL: GachaStaffCandidate[] = [
  // ==========================================
  // 1. BẾP CHIÊN (Cook) - 12 Model
  // ==========================================
  {
    id: 'cook_c1',
    name: 'Tí Lạc',
    role: 'cook',
    rarity: 'C',
    stars: 1,
    title: 'Phụ Bếp Tân Binh',
    avatar: '👨‍🍳',
    speed: 52,
    skill: 50,
    attitude: 75,
    stamina: 68,
    laziness: 22,
    errorRate: 15,
    hourlyWage: 19000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Học Việc Chăm Chỉ',
    passiveDesc: 'Chưa quen tay, thỉnh thoảng nhấc chảo hơi muộn.',
    quote: 'Dạ con mới vào làm, dầu bắn trúng con nhảy tưng tưng!',
    modelAsset: '/assets/staff/cook_c1.png'
  },
  {
    id: 'cook_c2',
    name: 'Bé Hạnh',
    role: 'cook',
    rarity: 'C',
    stars: 1,
    title: 'Chiên Khoai Part-time',
    avatar: '👩‍🍳',
    speed: 55,
    skill: 54,
    attitude: 82,
    stamina: 65,
    laziness: 20,
    errorRate: 14,
    hourlyWage: 20000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Lắc Khoai Rộn Ràng',
    passiveDesc: 'Thích lắc phô mai nhưng chiên gà còn lúng túng.',
    quote: 'Gà rán hay khoai tây lắc phô mai con làm được hết!',
    modelAsset: '/assets/staff/cook_c2.png'
  },
  {
    id: 'cook_c3',
    name: 'Văn Tèo',
    role: 'cook',
    rarity: 'C',
    stars: 1,
    title: 'Thợ Tẩm Bột Hè',
    avatar: '👦',
    speed: 48,
    skill: 52,
    attitude: 70,
    stamina: 72,
    laziness: 24,
    errorRate: 16,
    hourlyWage: 18000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Bột Phủ Đầy Quán',
    passiveDesc: 'Tẩm bột nhiệt tình nhưng bột văng lung tung.',
    quote: 'Bột chiên xù áo giáp 3 lớp chuẩn bài luôn sếp ơi!',
    modelAsset: '/assets/staff/cook_c3.png'
  },
  {
    id: 'cook_c4',
    name: 'Chị Mùi',
    role: 'cook',
    rarity: 'C',
    stars: 1,
    title: 'Bếp Phụ Chân Ướt',
    avatar: '👩',
    speed: 56,
    skill: 58,
    attitude: 88,
    stamina: 60,
    laziness: 18,
    errorRate: 12,
    hourlyWage: 21000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Tỉ Mỉ Cẩn Thận',
    passiveDesc: 'Làm chậm nhưng ít khi để gà bị sống bên trong.',
    quote: 'Thà chậm một chút mà khách ăn không đau bụng nghen!',
    modelAsset: '/assets/staff/cook_c4.png'
  },
  {
    id: 'cook_r1',
    name: 'Quang Đạt',
    role: 'cook',
    rarity: 'R',
    stars: 2,
    title: 'Bếp Lò Dày Dạn',
    avatar: '👨‍🍳',
    speed: 74,
    skill: 76,
    attitude: 80,
    stamina: 82,
    laziness: 10,
    errorRate: 6,
    hourlyWage: 29000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Gắp Nhanh Thoăn Thoắt',
    passiveDesc: 'Nhấc vỉ chiên chính xác, giảm 15% thời gian chiên.',
    quote: 'Cứ để chảo dầu đó cho tôi, 100 miếng vàng đều như 1!',
    modelAsset: '/assets/staff/cook_r1.png'
  },
  {
    id: 'cook_r2',
    name: 'Cô Năm',
    role: 'cook',
    rarity: 'R',
    stars: 2,
    title: 'Thợ Canh Lửa Gia Truyền',
    avatar: '👵',
    speed: 72,
    skill: 78,
    attitude: 90,
    stamina: 78,
    laziness: 8,
    errorRate: 5,
    hourlyWage: 32000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Mắt Nhìn Lửa Đỏ',
    passiveDesc: 'Canh chuẩn xác khoảnh khắc gà đạt màu hoàng kim.',
    quote: 'Dầu sôi nổi tim là vừa thả gà, nghe tiếng xèo là biết ngon!',
    modelAsset: '/assets/staff/cook_r2.png'
  },
  {
    id: 'cook_r3',
    name: 'Minh Khang',
    role: 'cook',
    rarity: 'R',
    stars: 2,
    title: 'Bếp Chiến Hẻm 1102',
    avatar: '👦',
    speed: 78,
    skill: 75,
    attitude: 85,
    stamina: 86,
    laziness: 9,
    errorRate: 6,
    hourlyWage: 31000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Chịu Nhiệt Bất Bại',
    passiveDesc: 'Đứng bếp liên tục không mệt mỏi trong giờ cao điểm.',
    quote: 'Nhiệt độ này nhằm nhò gì, bật bếp lên chiên tiếp đi sếp!',
    modelAsset: '/assets/staff/cook_r3.png'
  },
  {
    id: 'cook_r4',
    name: 'Bác Sáu Lò',
    role: 'cook',
    rarity: 'R',
    stars: 2,
    title: 'Cựu Đầu Bếp Quán Gà',
    avatar: '👴',
    speed: 70,
    skill: 80,
    attitude: 86,
    stamina: 80,
    laziness: 11,
    errorRate: 4,
    hourlyWage: 34000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Vỏ Giòn Bất Biến',
    passiveDesc: 'Gà để lâu trong khay giữ nhiệt vẫn giòn rụm.',
    quote: 'Kỹ thuật ép bột này bác học từ thời Pháp thuộc đó nghen!',
    modelAsset: '/assets/staff/cook_r4.png'
  },
  {
    id: 'cook_sr1',
    name: 'Huy Vũ',
    role: 'cook',
    rarity: 'SR',
    stars: 3,
    title: 'Nghệ Nhân Lửa Vàng',
    avatar: '🔥',
    speed: 90,
    skill: 92,
    attitude: 88,
    stamina: 90,
    laziness: 3,
    errorRate: 1,
    hourlyWage: 52000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Mẻ Chiên Hoàng Kim',
    passiveDesc: '+25% tỷ lệ mẻ chiên đạt Perfect, giảm 20% thời gian chiên.',
    quote: 'Gà rán dưới tay tôi không chỉ là đồ ăn, đó là nghệ thuật!',
    modelAsset: '/assets/staff/cook_sr1.png'
  },
  {
    id: 'cook_sr2',
    name: 'Mai Phương',
    role: 'cook',
    rarity: 'SR',
    stars: 3,
    title: 'Nữ Hoàng Cánh Gà Cay',
    avatar: '🌶️',
    speed: 88,
    skill: 94,
    attitude: 92,
    stamina: 86,
    laziness: 2,
    errorRate: 2,
    hourlyWage: 55000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol'],
    passiveName: 'Sốt Cay Thấm Đẫm',
    passiveDesc: 'Khách gọi món cánh sốt cay luôn tip thêm +3.000đ/phần.',
    quote: 'Cay xé lưỡi nhưng ai ăn xong cũng phải gật gù khen ngon!',
    modelAsset: '/assets/staff/cook_sr2.png'
  },
  {
    id: 'cook_sr3',
    name: 'Chef Long',
    role: 'cook',
    rarity: 'SR',
    stars: 3,
    title: 'Bếp Trưởng Nhượng Quyền',
    avatar: '👨‍🍳',
    speed: 92,
    skill: 90,
    attitude: 85,
    stamina: 92,
    laziness: 2,
    errorRate: 1,
    hourlyWage: 58000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Bảo Toàn Độ Sạch Dầu',
    passiveDesc: 'Dầu chiên chậm đen hơn 40%, tiết kiệm chi phí thay dầu.',
    quote: 'Quy chuẩn nhiệt độ và vệ sinh là danh dự của bếp trưởng!',
    modelAsset: '/assets/staff/cook_sr3.png'
  },
  {
    id: 'cook_ssr',
    name: 'Bác Ba Vàng',
    role: 'cook',
    rarity: 'SSR',
    stars: 5,
    title: 'Thần Bếp Sài Thành',
    avatar: '👑',
    speed: 98,
    skill: 99,
    attitude: 98,
    stamina: 96,
    laziness: 0,
    errorRate: 0,
    hourlyWage: 88000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss', 'night_owl'],
    passiveName: 'Đôi Tay Vàng Thần Bếp',
    passiveDesc: '100% mẻ chiên đạt Perfect, dầu sôi không hao hụt, tăng 25% doanh thu gà rán toàn quán!',
    quote: 'Một miếng gà rán ngon có thể làm bừng sáng cả một ngày u ám!',
    modelAsset: '/assets/staff/cook_ssr.png'
  },

  // ==========================================
  // 2. PHỤC VỤ (Waiter) - 12 Model
  // ==========================================
  {
    id: 'waiter_c1',
    name: 'Bé My',
    role: 'waiter',
    rarity: 'C',
    stars: 1,
    title: 'Lau Bàn Chân Ướt',
    avatar: '👧',
    speed: 54,
    skill: 48,
    attitude: 80,
    stamina: 62,
    laziness: 21,
    errorRate: 16,
    hourlyWage: 18000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Chấm Khăn Rụt Rè',
    passiveDesc: 'Lau bàn còn chậm, đôi khi làm rớt lọ tương.',
    quote: 'Dạ em lau bàn liền ạ, mong anh chị đừng chấm 1 sao!',
    modelAsset: '/assets/staff/waiter_c1.png'
  },
  {
    id: 'waiter_c2',
    name: 'Đức Thắng',
    role: 'waiter',
    rarity: 'C',
    stars: 1,
    title: 'Bưng Khay Mới Vào',
    avatar: '👦',
    speed: 50,
    skill: 52,
    attitude: 74,
    stamina: 70,
    laziness: 25,
    errorRate: 14,
    hourlyWage: 19000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Bước Chân Thận Trọng',
    passiveDesc: 'Đi từ từ sợ té, bưng 1 mâm mất khá nhiều thời gian.',
    quote: 'Em đang tập đi bước đôi cho khay đồ ăn khỏi sánh nước!',
    modelAsset: '/assets/staff/waiter_c2.png'
  },
  {
    id: 'waiter_c3',
    name: 'Kim Ngân',
    role: 'waiter',
    rarity: 'C',
    stars: 1,
    title: 'Nữ Sinh Part-time',
    avatar: '👩',
    speed: 58,
    skill: 50,
    attitude: 86,
    stamina: 58,
    laziness: 18,
    errorRate: 15,
    hourlyWage: 20000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Rót Nước Niềm Nở',
    passiveDesc: 'Khách uống nước rất vui nhưng bưng đồ nóng hơi run.',
    quote: 'Em mới học xong ca sáng là chạy thẳng qua quán phụ liền nè!',
    modelAsset: '/assets/staff/waiter_c3.png'
  },
  {
    id: 'waiter_c4',
    name: 'Hoàng Nam',
    role: 'waiter',
    rarity: 'C',
    stars: 1,
    title: 'Tiếp Thực Vụng Về',
    avatar: '🧑',
    speed: 52,
    skill: 46,
    attitude: 78,
    stamina: 66,
    laziness: 23,
    errorRate: 18,
    hourlyWage: 18000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Lẫn Lộn Bàn Số',
    passiveDesc: 'Đôi khi đưa món nhầm giữa bàn 1 và bàn 2.',
    quote: 'Ủa bàn này gọi khoai tây lắc phô mai hay tương cà ta?',
    modelAsset: '/assets/staff/waiter_c4.png'
  },
  {
    id: 'waiter_r1',
    name: 'Thảo Linh',
    role: 'waiter',
    rarity: 'R',
    stars: 2,
    title: 'Tiếp Viên Nhanh Nhảu',
    avatar: '👩',
    speed: 78,
    skill: 72,
    attitude: 88,
    stamina: 78,
    laziness: 9,
    errorRate: 6,
    hourlyWage: 28000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Lau Bàn Siêu Sạch',
    passiveDesc: 'Bàn ghế bóng loáng, tăng +0.1★ sao Vệ sinh cuối ngày.',
    quote: 'Bàn nào trống em dọn trong 3 nốt nhạc, sạch bong kin kít!',
    modelAsset: '/assets/staff/waiter_r1.png'
  },
  {
    id: 'waiter_r2',
    name: 'Tuấn Kiệt',
    role: 'waiter',
    rarity: 'R',
    stars: 2,
    title: 'Thanh Niên Tháo Vát',
    avatar: '👦',
    speed: 76,
    skill: 74,
    attitude: 82,
    stamina: 84,
    laziness: 8,
    errorRate: 5,
    hourlyWage: 30000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Bưng Khay Hai Tay',
    passiveDesc: 'Bưng cùng lúc 2 khay đồ ăn mà không hề run tay.',
    quote: 'Anh em cứ chiên gà thoải mái, khâu lên món để em lo!',
    modelAsset: '/assets/staff/waiter_r2.png'
  },
  {
    id: 'waiter_r3',
    name: 'Bích Trâm',
    role: 'waiter',
    rarity: 'R',
    stars: 2,
    title: 'Bàn Tròn Tươi Tắn',
    avatar: '👧',
    speed: 80,
    skill: 70,
    attitude: 90,
    stamina: 76,
    laziness: 7,
    errorRate: 5,
    hourlyWage: 31000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol'],
    passiveName: 'Khách Gọi Có Mặt',
    passiveDesc: 'Phản ứng nhanh với tiếng gọi của khách, giảm khách bỏ về.',
    quote: 'Khách cần khăn giấy hay thêm tương là em bay tới liền!',
    modelAsset: '/assets/staff/waiter_r3.png'
  },
  {
    id: 'waiter_r4',
    name: 'Minh Triết',
    role: 'waiter',
    rarity: 'R',
    stars: 2,
    title: 'Chuyên Viên Dọn Bàn',
    avatar: '🧑',
    speed: 74,
    skill: 78,
    attitude: 85,
    stamina: 80,
    laziness: 10,
    errorRate: 4,
    hourlyWage: 29000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Khử Trùng Tức Thì',
    passiveDesc: 'Khách ăn xong đứng dậy là dọn sạch ngay không delay.',
    quote: 'Vệ sinh sạch sẽ là nền tảng của một quán ăn uy tín!',
    modelAsset: '/assets/staff/waiter_r4.png'
  },
  {
    id: 'waiter_sr1',
    name: 'Yến Nhi',
    role: 'waiter',
    rarity: 'SR',
    stars: 3,
    title: 'Thiên Thần Phục Vụ',
    avatar: '🧚‍♀️',
    speed: 92,
    skill: 90,
    attitude: 96,
    stamina: 88,
    laziness: 3,
    errorRate: 2,
    hourlyWage: 50000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol'],
    passiveName: 'Nụ Cười Tỏa Nắng',
    passiveDesc: 'Khách ngồi tại bàn tăng 30% kiên nhẫn, +20% tiền tip.',
    quote: 'Chúc quý khách có một bữa ăn giòn tan và ngập tràn hạnh phúc!',
    modelAsset: '/assets/staff/waiter_sr1.png'
  },
  {
    id: 'waiter_sr2',
    name: 'Quốc Tuấn',
    role: 'waiter',
    rarity: 'SR',
    stars: 3,
    title: 'Trưởng Nhóm Sảnh Ăn',
    avatar: '🧹',
    speed: 90,
    skill: 92,
    attitude: 90,
    stamina: 92,
    laziness: 2,
    errorRate: 1,
    hourlyWage: 53000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Dọn Bàn Chớp Nhoáng',
    passiveDesc: 'Dọn sạch bàn trong 0.5 giây, cộng +0.2★ Vệ sinh cuối ngày.',
    quote: 'Sảnh tiệm gọn gàng thì khách ăn mới cảm thấy ngon miệng!',
    modelAsset: '/assets/staff/waiter_sr2.png'
  },
  {
    id: 'waiter_sr3',
    name: 'Hải Đăng',
    role: 'waiter',
    rarity: 'SR',
    stars: 3,
    title: 'Bậc Thầy Khay Mâm',
    avatar: '🍽️',
    speed: 94,
    skill: 88,
    attitude: 88,
    stamina: 94,
    laziness: 1,
    errorRate: 1,
    hourlyWage: 56000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Lên Món Tự Động',
    passiveDesc: 'Tự động kiểm tra và lên khay cho khách khi đồ ăn chín.',
    quote: 'Mắt tôi lia một vòng là biết bàn nào sắp thiếu món!',
    modelAsset: '/assets/staff/waiter_sr3.png'
  },
  {
    id: 'waiter_ssr',
    name: 'Bảo Trâm',
    role: 'waiter',
    rarity: 'SSR',
    stars: 5,
    title: 'Hoa Khôi Tiếp Tân Sài Gòn',
    avatar: '✨',
    speed: 99,
    skill: 98,
    attitude: 100,
    stamina: 96,
    laziness: 0,
    errorRate: 0,
    hourlyWage: 82000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol', 'future_boss'],
    passiveName: 'Dịch Vụ Hoàng Gia',
    passiveDesc: 'Tăng 40% sao Vệ Sinh & Không Gian, khách tip x2, triệt tiêu 100% phàn nàn của khách!',
    quote: 'Đến với tiệm gà của chúng em, mọi thực khách đều là thượng đế!',
    modelAsset: '/assets/staff/waiter_ssr.png'
  },

  // ==========================================
  // 3. THU NGÂN (Cashier) - 12 Model
  // ==========================================
  {
    id: 'cashier_c1',
    name: 'Bé Bống',
    role: 'cashier',
    rarity: 'C',
    stars: 1,
    title: 'Học Việc Máy POS',
    avatar: '👧',
    speed: 52,
    skill: 48,
    attitude: 82,
    stamina: 64,
    laziness: 22,
    errorRate: 17,
    hourlyWage: 19000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Thối Tiền Lẻ Rụt Rè',
    passiveDesc: 'Đếm tiền hơi lâu, đôi khi phải hỏi lại khách.',
    quote: 'Dạ tổng cộng là 45 ngàn... ủa dạ em thối lộn 5 ngàn nè!',
    modelAsset: '/assets/staff/cashier_c1.png'
  },
  {
    id: 'cashier_c2',
    name: 'Thanh Tùng',
    role: 'cashier',
    rarity: 'C',
    stars: 1,
    title: 'Mới Nhận Quầy',
    avatar: '👦',
    speed: 54,
    skill: 50,
    attitude: 76,
    stamina: 68,
    laziness: 24,
    errorRate: 15,
    hourlyWage: 18000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Bấm Phím Dò Dẫm',
    passiveDesc: 'Nhập đơn hàng vào hệ thống còn gián đoạn.',
    quote: 'Khách order từ từ giùm em nghen, màn hình hơi chói!',
    modelAsset: '/assets/staff/cashier_c2.png'
  },
  {
    id: 'cashier_c3',
    name: 'Lan Anh',
    role: 'cashier',
    rarity: 'C',
    stars: 1,
    title: 'Trực Quầy Ngơ Ngác',
    avatar: '👩',
    speed: 56,
    skill: 52,
    attitude: 84,
    stamina: 60,
    laziness: 20,
    errorRate: 13,
    hourlyWage: 20000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Nụ Cười Chữa Ngượng',
    passiveDesc: 'Khách thông cảm xí xóa khi tính tiền hơi chậm.',
    quote: 'Em cảm ơn anh chị nhiều lắm, bữa sau lại ghé ủng hộ em nha!',
    modelAsset: '/assets/staff/cashier_c3.png'
  },
  {
    id: 'cashier_c4',
    name: 'Khắc Huy',
    role: 'cashier',
    rarity: 'C',
    stars: 1,
    title: 'Thu Ngân Mùa Thi',
    avatar: '🧑',
    speed: 48,
    skill: 55,
    attitude: 72,
    stamina: 65,
    laziness: 25,
    errorRate: 16,
    hourlyWage: 18500,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Vừa Học Vừa Thu',
    passiveDesc: 'Dễ ngáp trong ca trưa nhưng tính toán số liệu khá chuẩn.',
    quote: 'Em vừa ôn bài triết vừa tính tiền gà, logic chuẩn xác luôn!',
    modelAsset: '/assets/staff/cashier_c4.png'
  },
  {
    id: 'cashier_r1',
    name: 'Bảo Anh',
    role: 'cashier',
    rarity: 'R',
    stars: 2,
    title: 'Zét-bi Tươi Tắn',
    avatar: '👧',
    speed: 78,
    skill: 72,
    attitude: 92,
    stamina: 80,
    laziness: 9,
    errorRate: 6,
    hourlyWage: 30000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol'],
    passiveName: 'Chào Khách Ngọt Ngào',
    passiveDesc: 'Khách đến quầy tăng ngay 15% kiên nhẫn.',
    quote: 'Dạ tiệm gà nhà tui xin chào! Hôm nay tiệm có đùi gà sốt cay ngon xỉu!',
    modelAsset: '/assets/staff/cashier_r1.png'
  },
  {
    id: 'cashier_r2',
    name: 'Thu Uyên',
    role: 'cashier',
    rarity: 'R',
    stars: 2,
    title: 'Tính Tiền Siêu Tốc',
    avatar: '👩',
    speed: 82,
    skill: 76,
    attitude: 85,
    stamina: 78,
    laziness: 8,
    errorRate: 5,
    hourlyWage: 32000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Quẹt Mã Không Trượt',
    passiveDesc: 'Thao tác quét mã QR và POS chỉ mất 1 giây.',
    quote: 'Chạm thẻ hay quét mã đều được hết ạ, tít tít xong ngay!',
    modelAsset: '/assets/staff/cashier_r2.png'
  },
  {
    id: 'cashier_r3',
    name: 'Hoàng Bách',
    role: 'cashier',
    rarity: 'R',
    stars: 2,
    title: 'Chàng Trai Quầy Thu',
    avatar: '👦',
    speed: 76,
    skill: 74,
    attitude: 88,
    stamina: 82,
    laziness: 10,
    errorRate: 5,
    hourlyWage: 31000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Gợi Ý Món Kèm',
    passiveDesc: '+15% xác suất khách gọi thêm nước ngọt ly to.',
    quote: 'Anh chị có muốn dùng thêm ly trà đào thanh mát giải ngấy không ạ?',
    modelAsset: '/assets/staff/cashier_r3.png'
  },
  {
    id: 'cashier_r4',
    name: 'Bích Phượng',
    role: 'cashier',
    rarity: 'R',
    stars: 2,
    title: 'Sổ Sách Rành Mạch',
    avatar: '👩',
    speed: 74,
    skill: 80,
    attitude: 84,
    stamina: 84,
    laziness: 7,
    errorRate: 4,
    hourlyWage: 33000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Khóa Sổ Không Lệch',
    passiveDesc: 'Cuối ngày kiểm kê quỹ tiền mặt chính xác 100%.',
    quote: 'Tiền bạc phân minh, một ngàn cũng phải vào đúng sổ sách!',
    modelAsset: '/assets/staff/cashier_r4.png'
  },
  {
    id: 'cashier_sr1',
    name: 'Diệu Nhi',
    role: 'cashier',
    rarity: 'SR',
    stars: 3,
    title: 'Hotgirl Quầy Thu',
    avatar: '💖',
    speed: 90,
    skill: 88,
    attitude: 96,
    stamina: 86,
    laziness: 3,
    errorRate: 1,
    hourlyWage: 54000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol'],
    passiveName: 'Hiệu Ứng Hút Fan',
    passiveDesc: 'Lượng khách ghé quán mỗi ngày tăng thêm +20%.',
    quote: 'Mấy bạn tới ăn gà nhớ quay TikTok gắn thẻ tiệm tụi mình nghen!',
    modelAsset: '/assets/staff/cashier_sr1.png'
  },
  {
    id: 'cashier_sr2',
    name: 'Trần Tuấn',
    role: 'cashier',
    rarity: 'SR',
    stars: 3,
    title: 'Thánh Upsell Combo',
    avatar: '💳',
    speed: 92,
    skill: 92,
    attitude: 90,
    stamina: 88,
    laziness: 2,
    errorRate: 1,
    hourlyWage: 57000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Bán Kèm Siêu Đẳng',
    passiveDesc: '+30% khách hàng tự động nâng cấp lên Combo siêu to khổng lồ.',
    quote: 'Chỉ thêm 15k là có ngay phần khoai phô mai và ly nước bự chà bá!',
    modelAsset: '/assets/staff/cashier_sr2.png'
  },
  {
    id: 'cashier_sr3',
    name: 'Khánh Chi',
    role: 'cashier',
    rarity: 'SR',
    stars: 3,
    title: 'Chuyên Gia Dòng Tiền',
    avatar: '📊',
    speed: 88,
    skill: 94,
    attitude: 92,
    stamina: 90,
    laziness: 1,
    errorRate: 0,
    hourlyWage: 60000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Quản Trị Doanh Thu',
    passiveDesc: '+10% tổng doanh thu thu được cuối ngày nhờ tối ưu dòng tiền.',
    quote: 'Một đồng tiết kiệm là một đồng lợi nhuận cho tiệm của chúng ta!',
    modelAsset: '/assets/staff/cashier_sr3.png'
  },
  {
    id: 'cashier_ssr',
    name: 'Vy Vivian',
    role: 'cashier',
    rarity: 'SSR',
    stars: 5,
    title: 'Nữ Hoàng Triệu View',
    avatar: '👑',
    speed: 98,
    skill: 99,
    attitude: 100,
    stamina: 95,
    laziness: 0,
    errorRate: 0,
    hourlyWage: 90000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['tiktok_idol', 'future_boss'],
    passiveName: 'Cơn Sốt Check-in Toàn Quốc',
    passiveDesc: 'Khách VIP sộp nườm nượp kéo đến, tăng 50% tiền Tip toàn tiệm, đánh giá 5★ tuyệt đối!',
    quote: 'Hello cả nhà yêu! Hôm nay cùng Vy ghé Tiệm Gà Nhà Tui giòn rụm nha!',
    modelAsset: '/assets/staff/cashier_ssr.png'
  },

  // ==========================================
  // 4. GIAO HÀNG (Delivery) - 12 Model
  // ==========================================
  {
    id: 'delivery_c1',
    name: 'Tèo Biker',
    role: 'delivery',
    rarity: 'C',
    stars: 1,
    title: 'Mới Mua Xe Cũ',
    avatar: '🛵',
    speed: 52,
    skill: 48,
    attitude: 78,
    stamina: 74,
    laziness: 22,
    errorRate: 16,
    hourlyWage: 19000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Lạc Đường Trong Hẻm',
    passiveDesc: 'Chưa thạo bản đồ, đôi khi tìm nhà hơi lâu.',
    quote: 'Alo anh ơi nhà mình quẹo cua số mấy dạ, em đang đứng ở cột điện!',
    modelAsset: '/assets/staff/delivery_c1.png'
  },
  {
    id: 'delivery_c2',
    name: 'Minh Tân',
    role: 'delivery',
    rarity: 'C',
    stars: 1,
    title: 'Shipper Sinh Viên',
    avatar: '👦',
    speed: 56,
    skill: 50,
    attitude: 82,
    stamina: 68,
    laziness: 20,
    errorRate: 14,
    hourlyWage: 20000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Sợ Chạy Trời Mưa',
    passiveDesc: 'Trời mưa gió chạy chậm để bảo đảm an toàn.',
    quote: 'Mưa to quá em trùm áo mưa kỹ lắm, hộp gà vẫn khô ráo nha sếp!',
    modelAsset: '/assets/staff/delivery_c2.png'
  },
  {
    id: 'delivery_c3',
    name: 'Văn Cường',
    role: 'delivery',
    rarity: 'C',
    stars: 1,
    title: 'Tài Xế Tà Tà',
    avatar: '🧑',
    speed: 46,
    skill: 52,
    attitude: 70,
    stamina: 75,
    laziness: 26,
    errorRate: 15,
    hourlyWage: 18000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Ngắm Cảnh Phố Phường',
    passiveDesc: 'Chạy thong thả, đơn app đôi khi bị chờ.',
    quote: 'Đường Sài Gòn đông đúc, cứ bình tĩnh từ từ tới nơi thôi sếp!',
    modelAsset: '/assets/staff/delivery_c3.png'
  },
  {
    id: 'delivery_c4',
    name: 'Bảo Long',
    role: 'delivery',
    rarity: 'C',
    stars: 1,
    title: 'Tay Lái Mới',
    avatar: '👦',
    speed: 50,
    skill: 46,
    attitude: 76,
    stamina: 70,
    laziness: 21,
    errorRate: 17,
    hourlyWage: 19500,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Khay Đồ Rung Lắc',
    passiveDesc: 'Qua gờ giảm tốc hơi gắt, đồ ăn dễ bị xộc xệch.',
    quote: 'Ổ gà sâu quá sếp ơi, may mà hộp gà kraft đóng gói chắc chắn!',
    modelAsset: '/assets/staff/delivery_c4.png'
  },
  {
    id: 'delivery_r1',
    name: 'Hoàng Shipper',
    role: 'delivery',
    rarity: 'R',
    stars: 2,
    title: 'Rành Đường Hẻm',
    avatar: '🧑',
    speed: 82,
    skill: 76,
    attitude: 84,
    stamina: 86,
    laziness: 9,
    errorRate: 6,
    hourlyWage: 30000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Bản Đồ Sống Hẻm 1102',
    passiveDesc: 'Giao nhanh các đơn lân cận trong bán kính 2km.',
    quote: 'Hẻm nào cụt hẻm nào thông em nắm trong lòng bàn tay hết!',
    modelAsset: '/assets/staff/delivery_r1.png'
  },
  {
    id: 'delivery_r2',
    name: 'Quốc Đạt',
    role: 'delivery',
    rarity: 'R',
    stars: 2,
    title: 'Nhanh Tay Bắt Đơn',
    avatar: '🛵',
    speed: 80,
    skill: 78,
    attitude: 82,
    stamina: 85,
    laziness: 8,
    errorRate: 5,
    hourlyWage: 32000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Bắn Đơn Nhanh Như Chớp',
    passiveDesc: 'Bắt đơn trên app ngay khi khách vừa đặt 1 giây.',
    quote: 'Tiếng chuông app nổ là xe em đã nổ máy sẵn sàng lăn bánh!',
    modelAsset: '/assets/staff/delivery_r2.png'
  },
  {
    id: 'delivery_r3',
    name: 'Thành Phong',
    role: 'delivery',
    rarity: 'R',
    stars: 2,
    title: 'Chiến Mã Wave Tàu',
    avatar: '🏍️',
    speed: 85,
    skill: 74,
    attitude: 80,
    stamina: 88,
    laziness: 10,
    errorRate: 5,
    hourlyWage: 31000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Luồn Lách Kẹt Xe',
    passiveDesc: 'Bỏ qua tác động của giờ cao điểm kẹt xe chiều tối.',
    quote: 'Kẹt xe đường lớn thì mình luồn hẻm nhỏ, không bao giờ trễ đơn!',
    modelAsset: '/assets/staff/delivery_r3.png'
  },
  {
    id: 'delivery_r4',
    name: 'Bá Hùng',
    role: 'delivery',
    rarity: 'R',
    stars: 2,
    title: 'Thùng Giữ Nhiệt Kín',
    avatar: '📦',
    speed: 76,
    skill: 82,
    attitude: 86,
    stamina: 84,
    laziness: 7,
    errorRate: 4,
    hourlyWage: 33000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Giữ Nóng Thần Tốc',
    passiveDesc: 'Đơn giao xa vẫn giữ độ nóng hổi và giòn tan.',
    quote: 'Thùng bạc cách nhiệt 3 lớp, giao tới nơi sờ vào vẫn phỏng tay!',
    modelAsset: '/assets/staff/delivery_r4.png'
  },
  {
    id: 'delivery_sr1',
    name: 'Vũ Lôi',
    role: 'delivery',
    rarity: 'SR',
    stars: 3,
    title: 'Tia Chớp Hẻm Sâu',
    avatar: '⚡',
    speed: 95,
    skill: 88,
    attitude: 86,
    stamina: 94,
    laziness: 2,
    errorRate: 1,
    hourlyWage: 52000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Tốc Biến Giao Hàng',
    passiveDesc: 'Đơn App hoàn thành nhanh hơn 40%, khách app tăng 35% kiên nhẫn.',
    quote: 'Chưa kịp ngâm nguội là chuông cửa nhà khách đã reng!',
    modelAsset: '/assets/staff/delivery_sr1.png'
  },
  {
    id: 'delivery_sr2',
    name: 'Tiến Bịp',
    role: 'delivery',
    rarity: 'SR',
    stars: 3,
    title: 'Trùm Chiết Khấu Sàn',
    avatar: '📱',
    speed: 90,
    skill: 92,
    attitude: 88,
    stamina: 90,
    laziness: 1,
    errorRate: 2,
    hourlyWage: 55000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Bóp Nghẹt Phí App',
    passiveDesc: 'Giảm hoa hồng sàn giao hàng từ 22% xuống thẳng 5%!',
    quote: 'Sàn app ăn dày quá hả? Để tôi thương lượng ép phí xuống tận đáy!',
    modelAsset: '/assets/staff/delivery_sr2.png'
  },
  {
    id: 'delivery_sr3',
    name: 'Hải Triều',
    role: 'delivery',
    rarity: 'SR',
    stars: 3,
    title: 'Bất Chấp Bão Bùng',
    avatar: '🌧️',
    speed: 92,
    skill: 90,
    attitude: 92,
    stamina: 96,
    laziness: 1,
    errorRate: 1,
    hourlyWage: 58000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Mưa Gió Nhân Đôi',
    passiveDesc: 'Khi trời mưa hoặc giông bão, đơn App tự động x2 doanh thu.',
    quote: 'Mưa càng lớn tôi chạy càng hăng, khách đói đang trông chờ tiệm mình!',
    modelAsset: '/assets/staff/delivery_sr3.png'
  },
  {
    id: 'delivery_ssr',
    name: 'Phong Thần Tài',
    role: 'delivery',
    rarity: 'SSR',
    stars: 5,
    title: 'Huyền Thoại Phượt Thủ 67',
    avatar: '🛵💨',
    speed: 99,
    skill: 98,
    attitude: 96,
    stamina: 100,
    laziness: 0,
    errorRate: 0,
    hourlyWage: 85000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss', 'night_owl'],
    passiveName: 'Bão Đơn Tốc Độ Hoàng Kim',
    passiveDesc: '100% đơn app đạt chuẩn Perfect, miễn phí 100% phí sàn, thưởng thêm 10.000đ mỗi đơn app!',
    quote: 'Bánh xe lăn tới đâu, hương thơm gà giòn lan tỏa tới đó!',
    modelAsset: '/assets/staff/delivery_ssr.png'
  },

  // ==========================================
  // 5. QUẢN LÝ (Manager) - 12 Model
  // ==========================================
  {
    id: 'manager_c1',
    name: 'Tập Sự Huy',
    role: 'manager',
    rarity: 'C',
    stars: 1,
    title: 'Mới Tốt Nghiệp F&B',
    avatar: '👔',
    speed: 50,
    skill: 54,
    attitude: 80,
    stamina: 66,
    laziness: 23,
    errorRate: 15,
    hourlyWage: 22000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Sách Vở Máy Móc',
    passiveDesc: 'Lý thuyết nhiều, gặp tình huống bất ngờ hơi lúng túng.',
    quote: 'Theo giáo trình quản trị trang 45 thì lúc này ta nên mở thêm bàn...',
    modelAsset: '/assets/staff/manager_c1.png'
  },
  {
    id: 'manager_c2',
    name: 'Chị Hạnh',
    role: 'manager',
    rarity: 'C',
    stars: 1,
    title: 'Phó Ca Tạm Thời',
    avatar: '👩‍💼',
    speed: 54,
    skill: 52,
    attitude: 85,
    stamina: 68,
    laziness: 20,
    errorRate: 13,
    hourlyWage: 24000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Ngại Nhắc Nhân Viên',
    passiveDesc: 'Tính tình hiền lành, chưa dám quát mắng khi nhân viên lười.',
    quote: 'Mấy đứa làm xong sớm rồi nghỉ tay chút nghen, đừng làm quá sức!',
    modelAsset: '/assets/staff/manager_c2.png'
  },
  {
    id: 'manager_c3',
    name: 'Thái Bảo',
    role: 'manager',
    rarity: 'C',
    stars: 1,
    title: 'Trực Ca Bỡ Ngỡ',
    avatar: '🧑‍💼',
    speed: 48,
    skill: 56,
    attitude: 75,
    stamina: 70,
    laziness: 25,
    errorRate: 16,
    hourlyWage: 21000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Đếm Bàn Chậm Rãi',
    passiveDesc: 'Phân phối chỗ ngồi khách vào giờ đông còn chậm.',
    quote: 'Quán đông quá ta, để em lấy sổ ra ghi thứ tự xếp hàng cái đã!',
    modelAsset: '/assets/staff/manager_c3.png'
  },
  {
    id: 'manager_c4',
    name: 'Kim Loan',
    role: 'manager',
    rarity: 'C',
    stars: 1,
    title: 'Thực Tập Quản Trị',
    avatar: '👩',
    speed: 52,
    skill: 50,
    attitude: 82,
    stamina: 64,
    laziness: 19,
    errorRate: 14,
    hourlyWage: 23000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Ghi Chép Nhiệt Tình',
    passiveDesc: 'Ghi nhật ký ca rất dài nhưng xử lý đơn chưa nhanh.',
    quote: 'Hôm nay tiệm bán được bao nhiêu cái đùi gà con ghi chép hết rồi nè!',
    modelAsset: '/assets/staff/manager_c4.png'
  },
  {
    id: 'manager_r1',
    name: 'Đức Trí',
    role: 'manager',
    rarity: 'R',
    stars: 2,
    title: 'Quản Lý Năng Nổ',
    avatar: '👨‍💼',
    speed: 78,
    skill: 76,
    attitude: 88,
    stamina: 82,
    laziness: 9,
    errorRate: 5,
    hourlyWage: 35000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Phân Bổ Ca Nhịp Nhàng',
    passiveDesc: 'Tăng +15% hiệu suất làm việc của toàn bộ nhân viên.',
    quote: 'Bếp chiên cứ tập trung chảo lửa, việc ngoài sảnh cứ để Trí sắp xếp!',
    modelAsset: '/assets/staff/manager_r1.png'
  },
  {
    id: 'manager_r2',
    name: 'Chị Thảo',
    role: 'manager',
    rarity: 'R',
    stars: 2,
    title: 'Bảo Mẫu Toàn Quán',
    avatar: '👩‍💼',
    speed: 75,
    skill: 78,
    attitude: 92,
    stamina: 80,
    laziness: 8,
    errorRate: 5,
    hourlyWage: 37000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Giữ Vững Sĩ Khí',
    passiveDesc: 'Nhân viên trong ca giảm 50% tốc độ tụt tâm trạng (Mood).',
    quote: 'Mấy đứa mệt thì uống miếng trà sữa chị mua, rồi cùng chiến tiếp nghen!',
    modelAsset: '/assets/staff/manager_r2.png'
  },
  {
    id: 'manager_r3',
    name: 'Hoàng Minh',
    role: 'manager',
    rarity: 'R',
    stars: 2,
    title: 'Cựu Trưởng Ca Fastfood',
    avatar: '🧑‍💼',
    speed: 80,
    skill: 74,
    attitude: 84,
    stamina: 84,
    laziness: 7,
    errorRate: 4,
    hourlyWage: 39000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Chuẩn Hóa Xếp Hàng',
    passiveDesc: 'Khách đứng chờ trật tự, giảm 20% tỷ lệ bực mình bỏ về.',
    quote: 'Một hàng lối ngăn nắp là nửa chặng đường của dịch vụ nhanh chóng!',
    modelAsset: '/assets/staff/manager_r3.png'
  },
  {
    id: 'manager_r4',
    name: 'Bích Hà',
    role: 'manager',
    rarity: 'R',
    stars: 2,
    title: 'Điều Phối Vững Tay',
    avatar: '👩‍💼',
    speed: 76,
    skill: 80,
    attitude: 86,
    stamina: 85,
    laziness: 8,
    errorRate: 4,
    hourlyWage: 38000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Hòa Giải Khiếu Nại',
    passiveDesc: 'Khách khó tính hoặc quạu được xoa dịu ngay lập tức.',
    quote: 'Chuyện lớn hóa nhỏ, chuyện nhỏ hóa không có gì, khách cứ an tâm!',
    modelAsset: '/assets/staff/manager_r4.png'
  },
  {
    id: 'manager_sr1',
    name: 'Bảo Khang',
    role: 'manager',
    rarity: 'SR',
    stars: 3,
    title: 'Nhà Khai Thác Tiềm Năng',
    avatar: '⭐',
    speed: 92,
    skill: 90,
    attitude: 92,
    stamina: 90,
    laziness: 2,
    errorRate: 1,
    hourlyWage: 60000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Truyền Lửa Chiến Binh',
    passiveDesc: 'Tăng +25% tốc độ và kỹ năng cho TOÀN BỘ nhân viên trong ca làm việc.',
    quote: 'Mỗi người chúng ta ở đây đều là một mắt xích không thể thay thế!',
    modelAsset: '/assets/staff/manager_sr1.png'
  },
  {
    id: 'manager_sr2',
    name: 'Quỳnh Nga',
    role: 'manager',
    rarity: 'SR',
    stars: 3,
    title: 'Chuyên Gia Tối Ưu Chi Phí',
    avatar: '📋',
    speed: 90,
    skill: 92,
    attitude: 90,
    stamina: 88,
    laziness: 1,
    errorRate: 1,
    hourlyWage: 63000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Thắt Chặt Hao Hụt',
    passiveDesc: 'Giảm 25% chi phí nguyên liệu và triệt tiêu phí rác thải thừa.',
    quote: 'Kiểm soát chặt chẽ từng gam bột, từng muỗng dầu, lợi nhuận sẽ nở hoa!',
    modelAsset: '/assets/staff/manager_sr2.png'
  },
  {
    id: 'manager_sr3',
    name: 'Eric Trần',
    role: 'manager',
    rarity: 'SR',
    stars: 3,
    title: 'Giám Sát Chuỗi Quốc Tế',
    avatar: '🏆',
    speed: 94,
    skill: 94,
    attitude: 88,
    stamina: 92,
    laziness: 1,
    errorRate: 0,
    hourlyWage: 66000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Quy Trình Chuẩn 5 Sao',
    passiveDesc: 'Tâm trạng nhân viên luôn khóa ở mức 100, +0.3★ Đánh giá tổng cuối ngày.',
    quote: 'Đưa tiêu chuẩn nhà hàng quốc tế về với hẻm nhỏ thân thương!',
    modelAsset: '/assets/staff/manager_sr3.png'
  },
  {
    id: 'manager_ssr',
    name: 'Madam Rose',
    role: 'manager',
    rarity: 'SSR',
    stars: 5,
    title: 'Tổng Quản Lý Huyền Thoại',
    avatar: '👑',
    speed: 98,
    skill: 100,
    attitude: 98,
    stamina: 96,
    laziness: 0,
    errorRate: 0,
    hourlyWage: 95000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss', 'night_owl'],
    passiveName: 'Nghệ Thuật Lãnh Đạo Tối Cao',
    passiveDesc: 'Tăng 50% hiệu suất cả tiệm, triệt tiêu 100% lỗi sai của mọi nhân viên, nhân đôi điểm uy tín quán!',
    quote: 'Khi một đội ngũ vận hành bằng cả trái tim, không đỉnh cao nào là không thể!',
    modelAsset: '/assets/staff/manager_ssr.png'
  },

  // ==========================================
  // 6. BẢO VỆ GIỮ XE (Security) - 12 Model
  // ==========================================
  {
    id: 'security_c1',
    name: 'Chú Bảy',
    role: 'security',
    rarity: 'C',
    stars: 1,
    title: 'Bảo Vệ Ghế Xếp',
    avatar: '👴',
    speed: 50,
    skill: 52,
    attitude: 78,
    stamina: 65,
    laziness: 25,
    errorRate: 16,
    hourlyWage: 18000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Gật Gù Bóng Cây',
    passiveDesc: 'Ngồi quạt nan dưới bóng râm, thỉnh thoảng chợp mắt.',
    quote: 'Cứ dựng xe đó đi con, có chú ngồi đây ngó giùm cho nghen!',
    modelAsset: '/assets/staff/security_c1.png'
  },
  {
    id: 'security_c2',
    name: 'Thanh Tuấn',
    role: 'security',
    rarity: 'C',
    stars: 1,
    title: 'Trông Xe Buổi Trưa',
    avatar: '👦',
    speed: 54,
    skill: 48,
    attitude: 80,
    stamina: 70,
    laziness: 22,
    errorRate: 15,
    hourlyWage: 19000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['phone_addict'],
    passiveName: 'Dắt Xe Lúng Túng',
    passiveDesc: 'Xe tay ga nặng dắt hơi chậm và mồ hôi nhễ nhại.',
    quote: 'Xe SH này nặng quá anh ơi, để em gạt chân chống nghiêng giùm cho!',
    modelAsset: '/assets/staff/security_c2.png'
  },
  {
    id: 'security_c3',
    name: 'Anh Út',
    role: 'security',
    rarity: 'C',
    stars: 1,
    title: 'Dân Phòng Tân Binh',
    avatar: '🧑',
    speed: 56,
    skill: 50,
    attitude: 84,
    stamina: 75,
    laziness: 20,
    errorRate: 14,
    hourlyWage: 20000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Còi Tu Huýt To',
    passiveDesc: 'Thổi còi nhắc nhở nhưng chưa có uy trước giang hồ.',
    quote: 'Bà con để xe sát lề giùm em, chừa lối đi cho xe rác qua với!',
    modelAsset: '/assets/staff/security_c3.png'
  },
  {
    id: 'security_c4',
    name: 'Bác Ba Đước',
    role: 'security',
    rarity: 'C',
    stars: 1,
    title: 'Gác Cửa Ban Chiều',
    avatar: '👴',
    speed: 48,
    skill: 54,
    attitude: 76,
    stamina: 68,
    laziness: 24,
    errorRate: 17,
    hourlyWage: 18500,
    mood: 100,
    shiftsWorked: 0,
    traits: ['clumsy'],
    passiveName: 'Mắt Nhìn Hơi Mờ',
    passiveDesc: 'Trời chập choạng tối nhìn biển số xe hơi chậm.',
    quote: 'Thẻ số 12 là xe chiếc Dream màu nho đúng hôn bây?',
    modelAsset: '/assets/staff/security_c4.png'
  },
  {
    id: 'security_r1',
    name: 'Chú Tư Dân Phòng',
    role: 'security',
    rarity: 'R',
    stars: 2,
    title: 'Nhiệt Huyết Khu Phố',
    avatar: '👮‍♂️',
    speed: 78,
    skill: 76,
    attitude: 90,
    stamina: 84,
    laziness: 9,
    errorRate: 6,
    hourlyWage: 29000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Trông Xe Chu Đáo',
    passiveDesc: 'Khách yên tâm ăn uống, giảm 30% rủi ro mất cắp.',
    quote: 'Xe ở đây có Tư canh, con kiến bò qua Tư cũng biết!',
    modelAsset: '/assets/staff/security_r1.png'
  },
  {
    id: 'security_r2',
    name: 'Anh Quyết',
    role: 'security',
    rarity: 'R',
    stars: 2,
    title: 'Cựu Bộ Đội Phục Viên',
    avatar: '🪖',
    speed: 80,
    skill: 78,
    attitude: 88,
    stamina: 88,
    laziness: 7,
    errorRate: 4,
    hourlyWage: 32000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Tác Phong Quân Đội',
    passiveDesc: 'Xếp xe thẳng tắp tăm tắp, khách vào là dắt quay đầu sẵn.',
    quote: 'Kỷ luật và trật tự! Khách bước ra là xe đã nổ máy chờ sẵn!',
    modelAsset: '/assets/staff/security_r2.png'
  },
  {
    id: 'security_r3',
    name: 'Dũng Râu',
    role: 'security',
    rarity: 'R',
    stars: 2,
    title: 'Hộ Pháp Cửa Tiệm',
    avatar: '🧔',
    speed: 74,
    skill: 80,
    attitude: 82,
    stamina: 90,
    laziness: 8,
    errorRate: 5,
    hourlyWage: 31000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Dáng Đứng Trầm Ngâm',
    passiveDesc: 'Tướng tá vạm vỡ khiến kẻ gian nhìn thấy là chùn bước.',
    quote: 'Thằng nào dám bén mảng tới quậy tiệm gà coi chừng nắm đấm của Dũng!',
    modelAsset: '/assets/staff/security_r3.png'
  },
  {
    id: 'security_r4',
    name: 'Bác Năm Trật Tự',
    role: 'security',
    rarity: 'R',
    stars: 2,
    title: 'Trật Tự Khu Phố 4',
    avatar: '👮',
    speed: 76,
    skill: 82,
    attitude: 86,
    stamina: 82,
    laziness: 9,
    errorRate: 5,
    hourlyWage: 30000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Thông Luồng Hẻm Sâu',
    passiveDesc: 'Không bao giờ để xảy ra cảnh tắc đường trước cửa tiệm.',
    quote: 'Hẻm thông thoáng thì lộc lá mới chảy vào quán được nghe con!',
    modelAsset: '/assets/staff/security_r4.png'
  },
  {
    id: 'security_sr1',
    name: 'Đại Ca Hổ',
    role: 'security',
    rarity: 'SR',
    stars: 3,
    title: 'Hiệp Sĩ Săn Bắt Cướp',
    avatar: '🐅',
    speed: 92,
    skill: 90,
    attitude: 88,
    stamina: 94,
    laziness: 2,
    errorRate: 1,
    hourlyWage: 50000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['night_owl'],
    passiveName: 'Mắt Thần Soi Gian',
    passiveDesc: 'Triệt tiêu 100% trộm xe, tóm gọn móc túi thưởng ngay +50.000đ tiền nóng.',
    quote: 'Mấy ngón nghề móc túi trộm xe này qua mắt anh Hổ sao được!',
    modelAsset: '/assets/staff/security_sr1.png'
  },
  {
    id: 'security_sr2',
    name: 'Chiến Binh Long',
    role: 'security',
    rarity: 'SR',
    stars: 3,
    title: 'Đặc Nhiệm Giải Ngũ',
    avatar: '🛡️',
    speed: 90,
    skill: 94,
    attitude: 90,
    stamina: 96,
    laziness: 1,
    errorRate: 1,
    hourlyWage: 54000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Dẹp Loạn Tức Thì',
    passiveDesc: 'Khóa chặt 100% sự cố giang hồ đòi nợ hay khách say xỉn đập bàn quỵt tiền.',
    quote: 'An ninh của quán là trách nhiệm thép, tôi bảo đảm an toàn tuyệt đối!',
    modelAsset: '/assets/staff/security_sr2.png'
  },
  {
    id: 'security_sr3',
    name: 'Võ Sư Hùng',
    role: 'security',
    rarity: 'SR',
    stars: 3,
    title: 'Đai Đen Vovinam',
    avatar: '🥋',
    speed: 94,
    skill: 92,
    attitude: 92,
    stamina: 92,
    laziness: 1,
    errorRate: 0,
    hourlyWage: 57000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss'],
    passiveName: 'Khí Phách Trấn Giữ',
    passiveDesc: 'Khách gia đình và người lớn tuổi yên tâm ghé quán đông hơn (+20% khách).',
    quote: 'Võ đạo là để bảo vệ lẽ phải và giữ gìn bình yên cho khu phố!',
    modelAsset: '/assets/staff/security_sr3.png'
  },
  {
    id: 'security_ssr',
    name: 'Chú Chín Đặc Nhiệm',
    role: 'security',
    rarity: 'SSR',
    stars: 5,
    title: 'Huyền Thoại Vệ Sĩ Thép',
    avatar: '👑',
    speed: 98,
    skill: 99,
    attitude: 98,
    stamina: 100,
    laziness: 0,
    errorRate: 0,
    hourlyWage: 85000,
    mood: 100,
    shiftsWorked: 0,
    traits: ['future_boss', 'night_owl'],
    passiveName: 'Bất Khả Xâm Phạm Hoàng Gia',
    passiveDesc: 'Bảo vệ tiệm tuyệt đối trước mọi nguy cơ cướp phá, thu hồi 100% nợ xấu, nhân đôi tiền tip khách đi xe hơi!',
    quote: 'Chừng nào Chín còn đứng đây, tiệm gà này an toàn hơn cả pháo đài!',
    modelAsset: '/assets/staff/security_ssr.png'
  }
];

// Hàm tìm nhân vật theo ID
export function getGachaStaffById(id: string): GachaStaffCandidate | undefined {
  return GACHA_STAFF_POOL.find(s => s.id === id);
}

// Lấy danh sách model theo vai trò
export function getStaffPoolByRole(role: StaffRole): GachaStaffCandidate[] {
  return GACHA_STAFF_POOL.filter(s => s.role === role);
}

// Lấy danh sách model theo độ hiếm
export function getStaffPoolByRarity(rarity: StaffRarity): GachaStaffCandidate[] {
  return GACHA_STAFF_POOL.filter(s => s.rarity === rarity);
}
