// SINH TỰ ĐỘNG bởi `npm run jev:content` (Jev · TypeSafe). Không sửa tay.
// Độ hài 0–4 của từng mẫu review (game ưu tiên câu hài hơn) và danh sách câu bị chặn vì phản cảm.
export const REVIEW_HUMOR: Readonly<Record<string, number>> = {
  "Trời ơi tin được không, tui order [ORDER] mà tiệm bưng ra cái món gì đâu không á! Ăn nói xà lơ dị? 1 sao trừ 100 điểm thanh lịch!": 2.44,
  "Nay đầu bếp bị người yêu đá hay sao mà lên sai món tùm lum vậy trời? Gọi đằng giao một nẻo, tức muốn trào đờm!": 2.3,
  "Bảng hiệu nhìn xịn mà làm ăn như giỡn mặt khách dị? Giao nhầm món xong còn không xin lỗi, cạch mặt tiệm từ nay!": 1.9,
  "Lần đầu ghé tiệm gà Bác Ba và cũng là lần cuối! Ship nhầm món cho khách mà thái độ huề cả làng, trap khách trắng trợn!": 2.24,
  "Tui dặn kỹ là [ORDER] mà bưng ra dĩa gì lạ hoắc. Hỏi lại thì kêu ráng ăn giùm, ủa tiền tui lá mít hả sếp?": 2.37,
  "Kiếp nạn thứ 82 của tui ở Hẻm 1102! Đợi nửa tiếng bưng ra dĩa đồ ăn của bàn khác, phục vụ lơ ngơ như bò đội nón.": 2.55,
  "Order gà không cay cho con nít ăn mà tiệm tọng nguyên dĩa gà sốt cay nồng, xém tí sặc nhập viện! Làm ăn cẩu thả quá!": 1.82,
  "Một pha xử lý cồng kềnh đi vào lòng đất! Đơn [ORDER] biến mất không dấu vết, giao đại món ế cho khách. Quá thất vọng!": 1.85,
  "Bị nhầm đơn mà mặt thu ngân tỉnh bơ như chưa hề có cuộc chia ly. Coi thường thời gian của thực khách vừa thôi nghen!": 2.22,
  "Ủa alo tiệm gà ơi? Em gọi [ORDER] chứ đâu gọi combo thất vọng này? Đề nghị đổi đầu bếp gấp!": 2.07,
  "Đợi gà mà ngỡ như đợi crush hồi âm, muốn mọc rễ ở quán luôn á sếp ơi! Đói hoa cả mắt cuối cùng phải bỏ về ăn mì tôm 😤": 2.75,
  "Khách đứng đợi tràn ra đầu hẻm mà tiệm làm rề rà phát bực. 40 phút không ra được một dĩa gà, flop toàn tập!": 1.41,
  "Đợi lâu tới mức người yêu giận đòi chia tay luôn rồi đồ ăn mới ra... 1 sao vì làm tổn thương sâu sắc tình cảm lứa đôi!": 2.55,
  "Huhu đói lả người giữa trưa nắng Sài Gòn, nhìn bàn bên nhai rôm rốp mà mình đứng đợi mòn mỏi. Tuyển thêm người đi chủ quán ơi!": 1.83,
  "Shipper nhận đơn đứng đợi tới mức bị hủy cuốc, trừ luôn tiền tài khoản. Quán bán buôn kiểu này ai dám nhận đơn nữa?": 1.5,
  "Thanh xuân của em trôi qua nửa đời người chỉ để chờ 1 dĩa [ORDER]... Đợi không nổi đành dắt xe đi về trong cay đắng.": 2.37,
  "Quán làm ăn như phim quay chậm Slow Motion! Bàn vô sau thì có trước, bàn mình thì bặt vô âm tín, đành nhịn đói rút lui!": 2.34,
  "Đói tụt đường huyết đứng tựa cột đèn ngóng đầu bếp chiên gà mà lòng đau như cắt. Thôi xin kiếu, không bao giờ quay lại!": 2.59,
  "Order lúc trời còn nắng chói chang, tới lúc sao lên mọc đầy trời vẫn chưa thấy tăm hơi dĩa gà. Bỏ về ngủ cho lành!": 1.96,
  "Đứng chờ tới mức con mèo của quán chạy qua liếm chân 3 bận mà đơn vẫn đang chế biến. Đành ngậm ngùi chào thân ái và quyết thắng!": 2.61,
  "Gà thì ăn cũng được mà tốc độ làm món như rùa bò đi dạo phố á. Đi ăn giờ nghỉ trưa mà trễ giờ chấm công luôn nè!": 2.23,
  "Món ăn tạm ổn nhưng đợi gần 30 phút sốt hết cả ruột. Mong chủ quán đầu tư thêm bếp chiên tốc độ cao chứ vầy oải quá.": 1.22,
  "Ăn một miếng gà mà chờ cả nửa buổi chiều. Khách đông thì phải báo trước để người ta liệu đường chứ để khách ngồi ngóng hoài.": 1.46,
  "Tay nghề chiên gà được nhưng thao tác tay còn lóng ngóng vụng về quá. Bác Ba huấn luyện lại nhân viên cho nhanh nhẹn nghen!": 1.2,
  "Ly nước ngọt đá tan thành nước lọc luôn rồi mới thấy dĩa gà bê ra! Trừ 2 sao vì làm nhạt nhòa ly nước ngọt của tui.": 1.79,
  "Quán trong hẻm mà phong cách làm việc thong thả như nghỉ dưỡng resort vậy á. Ai đang vội thì né gấp quán này ra nha!": 2.38,
  "Gà giòn thơm nhưng chờ lâu quá làm tụt hết cả mood thèm ăn. Cần cải thiện quy trình ra món gấp!": 0.77,
  "Đợi đồ ăn mà kịp lướt hết 50 clip TikTok vẫn chưa thấy đồ ăn. Cho 3 sao khích lệ tinh thần cố gắng lần sau.": 2.29,
  "Gà chiên bị khét đen thùi lùi như tiền đồ của mình vậy á. Cắn một miếng đắng nghét khóc thét, cứu tui trời ơi!": 2.89,
  "Miếng gà cháy đen như than củi, vỏ đắng nghét mà bên trong thì khô queo. Bếp ơi làm ơn có tâm giùm xíu đi ạ!": 1.81,
  "Cắn miếng da gà tính tận hưởng mà vị khét lẹt nồng nặc cả khoang miệng. Nay bếp lơ là dữ nha, trừ sạch điểm hương vị!": 1.92,
  "Chiên gà hay đốt than vậy tiệm? Đưa dĩa gà cháy đen thui cho khách mà lấy tiền trọn vẹn không biết ngại hả?": 2.03,
  "Vỏ gà khét đắng ngắt, lột hết da ra thì thịt bên trong bở rệp. Trải nghiệm tệ hại nhất tuần này!": 1.36,
  "Tui dắt crush đi ăn mà tiệm bưng ra dĩa gà khét đen sì, quê xệ với crush luôn á! 1 sao không nói nhiều!": 2.39,
  "Đầu bếp mải buôn chuyện hay bấm điện thoại mà để chảo cháy khói um sùm vậy? Mùi khét ám vô đồ ăn không nuốt nổi.": 1.56,
  "Ăn gà rán mà ngỡ như đang gặm cục than tổ ong. Coi chừng ung thư nha cả nhà, né mẻ cháy của quán này ra!": 2.42,
  "Lửa canh trật lất, bên ngoài cháy xém bên trong còn đỏ máu tanh tanh. Kỹ thuật chiên quá non nớt!": 1.86,
  "Biết là quán đông nhưng cháy thì phải bỏ mẻ khác chiên lại chứ sao lại cố giao cho khách? Mất uy tín quá Bác Ba ơi!": 1.15,
  "Dầu chiên đen sì như hắc ín, miếng gà bám đầy cặn đen. Chủ tiệm tiếc tiền thay dầu hay gì? Ăn xong về ôm bụng cả đêm!": 1.82,
  "Nồng nặc mùi dầu cũ khét lẹt, ăn hai miếng là ngấy tận óc. Làm ăn vầy rồi sao giữ chân khách quen được Bác Ba?": 1.82,
  "Miếng gà sũng dầu cũ ngả màu nâu đen, nhìn mất vệ sinh thực sự. Đề nghị đoàn kiểm tra ATTP ghé thăm đột xuất!": 0.76,
  "Nhìn vô chảo dầu đen thui như nước cống mà rùng mình gai ốc. Khuyên thật lòng tiệm nên thay dầu thường xuyên hơn!": 1.92,
  "Ăn xong dĩa gà về nhà là bụng réo rắt, tào tháo rượt suốt 3 tiếng đồng hồ. Tiếc tiền thay dầu hại sức khỏe khách hàng!": 1.99,
  "Miếng bột chiên dính đầy cặn khét màu đen li ti. Dầu tái chế chiên đi chiên lại nhiều lần chắc luôn!": 1.44,
  "Mùi dầu hôi nồng nặc bay khắp cả con hẻm. Vừa cắn miếng gà nghe mùi dầu cũ sặc lên mũi phát nôn.": 1.12,
  "Vệ sinh quán là trên hết mà để chảo dầu bẩn kinh hoàng. Tẩy chay cho tới khi tiệm công khai quy trình thay dầu sạch!": 1.06,
  "Ủa bán gà dát vàng 24k hay sao mà chém giá khét lẹt dị? Ăn xong mở ví ra thấy bay màu nửa tháng tiền trọ, khóc ròng!": 2.67,
  "Miếng gà bé xíu xiu bằng nắm tay mà giá cao ngất ngưởng. Giá này chỉ dành cho đại gia chứ sinh viên tụi em xin kiếu!": 2.11,
  "Đồ ăn cũng tạm được mà bill tính ra chát chúa quá, không có combo hay voucher gì hết trơn. Chắc không dám quay lại lần hai.": 0.95,
  "Quán vỉa hè hẻm nhỏ mà bán giá ngang ngửa nhà hàng trung tâm thương mại! Định vị giá kiểu này coi chừng mất khách sớm.": 1.44,
  "Tính tiền thêm lon nước ngọt mà giá x2 tạp hóa đầu ngõ. Cảm giác bị vặt lông gà không thương tiếc!": 2.03,
  "Ăn chưa kịp no bụng mà ví đã xẹp lép như bánh tráng. Tiệm nên có combo tiết kiệm cho học sinh sinh viên nhờ.": 2.2,
  "Chất lượng tầm 7 điểm mà giá set 10 điểm. Không tương xứng với số tiền bỏ ra, hơi hối hận khi ghé.": 1.12,
  "Đọc menu thấy rẻ mà tính tiền ra đủ loại phụ phí. Làm ăn không minh bạch gì hết trơn à!": 1.03,
  "Trời SG 38 độ hầm hập mà quán ngồi ghế nhựa vỉa hè khói bụi tạt vô mặt, ăn miếng gà mà mồ hôi ướt đẫm cả áo!": 1.85,
  "Quán trong hẻm chật chội chen chúc nhau ngột ngạt ghê. Hy vọng chủ tiệm sớm mở rộng không gian cho thoáng đãng hơn.": 0.49,
  "Khói chiên dầu từ bếp xộc thẳng vô mặt thực khách ngộp thở muốn xỉu. Lắp thêm quạt hút khói đi chủ tiệm ơi!": 1.63,
  "Bàn ghế kê sát sàn sạt, khách đi qua quẹt trúng đĩa đồ ăn xém rớt. Chỗ ngồi quá tù túng, mất cả ngon!": 1.45,
  "Trời mưa một phát là nước tạt ướt mèm cả giỏ xách lẫn dĩa gà rán. Mái hiên tiệm dột tứ tung cần sửa lại gấp!": 1.39,
  "Tiếng còi xe ngoài hẻm inh ỏi, quán lại không mở nhạc chill át bớt. Ăn bữa gà mà nhức cả màng nhĩ.": 1.22,
  "Chỗ để xe không có người trông, vừa ăn vừa phải ngoái đầu dòm xe máy sợ bị bẻ khóa. Tâm trạng bất an dữ dội!": 1.54,
  "Đèn đóm trong hẻm tù mù tối thui, chụp hình sống ảo da bị ám vàng nhìn ghê quá. Cần thêm đèn neon lung linh!": 1.51,
  "Nhanh như một cơn gió! Vừa quét mã xong tính ngồi lướt TikTok thì khay gà nóng hổi đã bưng ra trước mặt. Tốc độ đỉnh chóp!": 1.83,
  "Phục vụ nhanh hơn người yêu cũ trở mặt! Gà bốc khói nghi ngút, giòn tan rôm rốp vừa thổi vừa ăn cưng xỉu!": 2.74,
  "Giao đồ ăn cả ngày đói lả ghé mua 1 phần gà popcorn, tiệm lên món cái rẹt kịp chạy cuốc tiếp, còn tặng thêm ly nước lạnh. Ấm lòng shipper!": 1.67,
  "Đúng chuẩn thức ăn nhanh! Order phát là có liền trong 3 nốt nhạc, gà vẫn nóng phỏng lưỡi, không hề chiên sẵn nguội ngắt.": 1.82,
  "Giờ cao điểm đông nghẹt mà bếp ra món như máy dập, phục vụ tay thoăn thoắt không kịp thở. Bái phục sự chuyên nghiệp!": 1.4,
  "Tốc độ ánh sáng là có thật! Vừa đặt mông xuống ghế là đồ ăn đã dọn ra tươm tất. Cho tiệm 5 sao tốc độ tên lửa!": 2.26,
  "Đi ăn trưa với sếp cần ăn lẹ để về họp, tiệm phục vụ đúng 5 phút xong nguyên combo [ORDER]. Cứu nguy một bàn thua trông thấy!": 2.43,
  "Quy trình order và lấy món mượt mà như bôi dầu trơn. Thao tác siêu nhanh mà không hề bị lộn đơn, quá xuất sắc!": 1.6,
  "Bác Ba chiên gà điêu luyện, phụ bếp bốc món liền tay, khách vô nườm nượp mà xử lý ngọt xớt. Quá nể phục!": 1.31,
  "Tụi mình đói lả sau giờ tập gym, vừa tấp vô gọi món là khay gà vàng ươm đã hạ cánh an toàn. Phục vụ nhiệt tình 10/10!": 1.51,
  "Nhanh - Gọn - Nóng sốt! Không phải đứng chờ một giây nào thừa thãi. Xứng đáng là địa chỉ ăn vặt số 1 cho người bận rộn.": 1.07,
  "Bấm gọi món xong chưa kịp rút điện thoại ra soi gương là đồ ăn đã bưng tới bàn. Nhanh hết hồn chim én luôn á!": 2.43,
  "Đỉnh nóc kịch trần bay phấp phới! Da gà giòn rụm rôm rốp, thịt bên trong mềm ngọt mọng nước chấm sốt cay bơ tỏi nhức nách!": 2.58,
  "Vừa cắn một miếng gà mà ngỡ như lạc vào thiên đường ẩm thực! Bác Ba chiên gà đúng chuẩn nghệ nhân Hẻm 1102!": 1.46,
  "Gà sốt mật ong tỏi ở đây là đỉnh của chóp! Vị đậm đà thấm từng thớ thịt, ăn xong thèm muốn xỉu, ngày mai ghé tiếp!": 1.18,
  "Một buổi chiều mưa ngồi dưới mái hiên số 14, vị giòn tan của miếng gà nóng hổi như đánh thức ký ức Sài Gòn xưa. Bác Ba truyền nghề khéo quá!": 0.58,
  "Thách thức 24h ăn sập Tiệm Gà Nhà Tui: Gà giòn vỏ mỏng rộp rộp, sốt cay tê lưỡi, đáng tiền từng xu! Đã đăng clip lên TikTok 1M fl nha sếp!": 2.27,
  "Lớp bột chiên vàng óng ánh không hề bị ngấy dầu, cắn vô nghe cái rôm rốp sướng rơn cả màng nhĩ. Mê chữ ê kéo dàiii!": 2.31,
  "Má đùi chiên sốt cay Yangnyeom ở đây ngon nuốt lưỡi! Thịt tươi ngọt tự nhiên chứ không hề có mùi đông lạnh công nghiệp. 10 điểm!": 1.06,
  "Phô mai que kéo sợi dài cả thước, vỏ ngoài giòn rụm bên trong béo ngậy. Ăn kèm sốt tương ớt chua ngọt của tiệm là chuẩn bài!": 0.96,
  "Gà popcorn lắc bột phô mai thơm nức mũi cả góc phố. Mua một hộp tính vừa đi bộ vừa nhâm nhi mà 2 phút hết veo vì quá ngon!": 1.54,
  "Vị đậm đà miền Nam pha chút cay nồng Hàn Quốc độc lạ chưa từng thấy ở quán nào khác. Tiệm giữ bí kíp này kỹ nghen!": 1.03,
  "Món củ cải muối vàng ăn kèm giải ngấy siêu đỉnh! Miếng gà chiên giòn rụm kẹp miếng củ cải giòn sần sật ăn hoài không biết chán.": 1.19,
  "Canh lửa xuất sắc! Bột chiên giòn tan nhưng thịt bên trong vẫn ươm hồng mọng nước, không bị khô xơ chút nào. Đẳng cấp Master Chef!": 1.1,
  "Miếng gà ngon tới mức nhỏ bạn đi chung đòi ăn cướp luôn phần của tui! Hai đứa xém uýnh lộn vì miếng gà cuối cùng haha!": 2.41,
  "Hương vị tuổi thơ xen lẫn hiện đại. Miếng gà rán làm tui nhớ những buổi chiều theo mẹ đi chợ ăn vặt. Ấm áp vô cùng!": 0.93,
  "Bánh biscuit mật ong thơm bơ ngầy ngậy, kết hợp gà cay giòn rụm đúng điệu Soul Food Mỹ nhưng mang hồn Sài Gòn. Quá nể!": 1.28,
  "Sốt bơ tỏi đậu nành quyện đều từng thớ gà óng ả, vị ngọt mặn hài hòa ăn dính miệng dã man. Món này phải gọi là cực phẩm!": 1.39,
  "Rẻ rúng bất ngờ luôn á trời! Combo no cành hông mà giá học sinh sinh viên siêu hạt dẻ. Chân ái cứu đói cuối tháng là đây!": 2.15,
  "Ăn ngập mặt từ gà giòn đến khoai lắc phô mai mà chia ra mỗi đứa có mấy chục ngàn. Quá hời cho một bữa đại tiệc thịnh soạn!": 1.76,
  "Tan học đói rã rời tấp vô tiệm làm combo gà giòn 25k no tới tối, nước sốt mật ong thơm lừng. Quán ruột của cả trường tụi em!": 1.62,
  "Giá cả bình dân đúng chất Hẻm 1102 tình nghĩa xóm giềng! Không hề nâng giá chặt chém người lao động, trân quý tiệm lắm!": 1.41,
  "Cầm tờ 50k bước vô tiệm mà bước ra no căng rốn, còn được thối lại tiền lẻ. Thời buổi bão giá tìm được quán vầy hiếm có khó tìm!": 2.3,
  "Menu thiết kế các combo thông minh, đi nhóm 3-4 người gọi share ra rẻ bèo nhèo luôn. Vote 5 sao nhiệt liệt!": 1.48,
  "Thực khách ruột từ những ngày đầu xe đẩy. Dù giờ tiệm khang trang hơn nhưng giá vẫn giữ vẹn nguyên sự tử tế. Cảm ơn Bác Ba!": 0.6,
  "Chất lượng sánh ngang gà các thương hiệu lớn mà giá chỉ bằng một nửa. Lựa chọn số một cho ví tiền sinh viên tụi mình!": 1.02,
  "Tiệm gà vị cứu tinh của các anh em văn phòng những ngày chờ lương về. Ngon - Bổ - Rẻ có thiệt trên đời nha quý dị!": 2.29,
  "Mua mang về được tặng thêm tương ớt, khăn lạnh đầy đủ không tính thêm xu nào. Bán buôn xởi lởi trời cho nghen chủ tiệm!": 1.59,
  "Góc check-in Gà Bông cưng xỉu up xỉu down! Máy lạnh mát rượi, nhạc lofi chill phết, chụp 800 tấm hình sống ảo cháy máy!": 2.29,
  "View phòng kính nhìn ra hẻm phố lung linh cực sang! Không gian ấm cúng, vừa ăn gà giòn vừa tâm sự với người yêu là số dách.": 1.15,
  "Tiệm trang trí phong cách bistro Hàn Quốc sáng sủa, tone màu caramel gỗ ấm cúng. Ngồi ăn cảm giác nhẹ nhàng, chữa lành tâm hồn!": 0.52,
  "Bảng hiệu neon nổi bật đầu hẻm chụp hình ban đêm siêu nghệ! Bàn ghế sạch bóng, khoảng cách ngồi rộng rãi thoải mái.": 0.71,
  "Quán có bé mèo tam thể mập ú nằm ngủ gật ở hiên cưng xỉu! Vừa ăn gà vừa được vuốt mèo xả stress sau giờ làm việc căng thẳng.": 2.24,
  "Máy lạnh phà mát rượi đập tan cái nóng bức 40 độ ngoài đường. Vô đây ăn dĩa gà uống ly coca mát lạnh là thiên đường!": 1.28,
  "List nhạc của tiệm có gu đỉnh thực sự! Toàn indie Việt với lofi nhẹ nhàng, ngồi học bài hay làm việc nhóm đều cực hợp lý.": 0.73,
  "Khu vực quầy bếp mở lắp kính trong suốt nhìn đầu bếp chiên gà thoăn thoắt rất an tâm và thích mắt. Decor rất tinh tế!": 0.36,
  "Đèn lồng vàng treo dọc mái hiên số 14 tạo cảm giác hoài niệm Sài Gòn thập niên 90. Một góc quán quá đỗi bình yên giữa phố thị.": 0.19,
  "Bãi giữ xe có Chú Tư bảo vệ dắt xe tận tình, che mưa che nắng chu đáo. Điểm 10 cho sự hiếu khách từ ngoài cửa!": 1,
  "Quán sạch bong kin kít! Dầu chiên vàng óng thơm phức, bếp mở nhìn thấy từng khâu yên tâm tuyệt đối 10/10!": 1.12,
  "Tiệm gà ngăn nắp, bàn ghế xếp trật tự không lấn lòng lề đường, dầu mỡ thu gom chuẩn. Điểm cộng lớn cho ý thức cộng đồng của tiệm!": 0.46,
  "Nhân viên đeo bao tay, tạp dề và khẩu trang chuẩn chỉnh khi chế biến. Ăn gà ở đây không bao giờ phải lo đau bụng!": 0.38,
  "Chảo dầu trong veo không một hạt cặn khét! Khay inox GN đựng thức ăn sáng loáng soi gương được. Rất hài lòng về độ sạch!": 1.29,
  "Khách vừa đứng dậy là nhân viên cầm chai xịt khuẩn lau bàn sạch bong liền. Quy trình khử trùng rất chuyên nghiệp!": 0.6,
  "Đồ đựng mang về dùng hộp giấy thân thiện môi trường thay vì hộp xốp độc hại. Vừa sạch sẽ vừa bảo vệ thiên nhiên!": 0.18,
  "Nguyên liệu gà để trong tủ bảo ôn mát lạnh nhìn tươi roi rói. Tiêu chuẩn an toàn vệ sinh xứng đáng nhận chứng nhận 5 sao!": 0.76,
  "Khu vực quầy tương sạch sẽ tinh tươm, không hề có tình trạng tương chảy dính nhớp nháp. Chăm chút từng chi tiết nhỏ!": 0.3,
  "Một trải nghiệm ẩm thực 10 điểm không có nhưng! Gà giòn, sốt ngon, phục vụ dễ thương, xứng đáng là quán ruột số 1 Sài Gòn!": 1.32,
  "Từ chủ tiệm tới nhân viên ai cũng nở nụ cười tươi rói chào đón khách. Ăn dĩa gà mà thấy ấm áp tình người miền Tây sông nước!": 0.81,
  "Tuần nào cũng phải ghé tiệm ít nhất 3 lần mới chịu nổi cơn ghiền. Tiệm gà gây nghiện nhất khu vực này rồi!": 1.27,
  "Mang bạn bè từ quê lên ăn thử ai cũng khen nức nở. Tự hào giới thiệu tiệm gà đặc sản Hẻm 1102 cho mọi người!": 0.62,
  "Chất lượng đồng đều từ ngày đầu khai trương tới giờ, không hề bị xuống phong độ khi đông khách. Rất đáng nể!": 0.17,
  "Ăn gà ở đây thấy lòng nhẹ bẫng sau một ngày làm việc áp lực. Cảm ơn tiệm đã luôn giữ lửa yêu nghề!": 0.7,
  "Bác Ba với chủ quán nói chuyện có duyên dữ dội, khách vô ăn mà cười rôm rả cả quán. Vừa ngon miệng vừa vui tai!": 1.6,
  "Gà rán chuẩn vị gia đình ấm cúng. Chúc tiệm buôn may bán đắt, sớm mở thêm nhiều chi nhánh lớn mạnh nha!": 0.19,
  "Đã bookmark tiệm vào danh sách những địa điểm ăn ngon nhất định phải ghé khi tới Sài Gòn. Quá xuất sắc!": 0.35,
  "Mọi thứ từ món ăn, nước chấm cho tới ly nước đá đều chỉn chu hoàn hảo. 5 sao không có gì phải đắn đo!": 0.16
};

export const REVIEW_BLOCKED: readonly string[] = [];
